// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:doodle_pad/app/data/models/drawing.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DrawingAdapter());
    registerAdapter(SerializableStrokeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DrawingAdapter());
    registerAdapter(SerializableStrokeAdapter());
  }
}
