import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'), // 미국 영어
    Locale('ko'), // 대한민국 한국어
    Locale('ja'), // 일본어
    Locale('de'), // 독일어
    Locale('ru'), // 러시아어
    Locale('fr'), // 프랑스어
    Locale('es'), // 스페인어
    Locale('pt'), // 포르투갈어
    Locale('id'), // 인도네시아어
    Locale('zh'), // 중국어
    Locale('ar'), // 아랍어
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Draw freely and share',
      'ask_before_clear': 'Confirm before clearing',
      'ask_before_clear_desc':
          'Ask for confirmation before erasing all strokes',
      'back': 'Back',
      'brush_guide_desc':
          'Change brushes below and drag the slider to adjust size',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'clear_canvas': 'Clear Canvas',
      'clear_canvas_confirm': 'Clear all content on the canvas?',
      'clear_data': 'Clear Local Data',
      'clear_data_complete': 'Local data is cleared.',
      'clear_data_confirm': 'Clear local settings and activity history?',
      'clear_data_desc': 'Reset app settings and activity history',
      'confirm': 'Confirm',
      'pick_color': 'Pick a Color',
      'canvas_color': 'Canvas Color',
      'canvas_color_desc': 'Choose a paper color for the canvas',
      'data_and_support': 'Data & Support',
      'drawing_settings': 'Drawing Settings',
      'eraser_mode': 'Eraser Mode',
      'error': 'Error',
      'exit': 'Exit',
      'exit_app_message': 'Your saved drawings stay on this device.',
      'exit_confirmation': 'Exit the app?',
      'feature_colors': 'Multiple Colors',
      'feature_eraser': 'Eraser',
      'feature_marker': 'Marker',
      'feature_pen': 'Pen',
      'feature_share': 'Share',
      'feature_undo': 'Undo',
      'feedback': 'Send Feedback',
      'feedback_desc': 'Share feedback',
      'feedback_email_subject': 'App Feedback',
      'haptic_feedback': 'Haptic Feedback',
      'haptic_feedback_desc': 'Vibrate with tools',
      'language': 'Language',
      'premium_benefit_remove_ads': 'Remove Ads',
      'premium_benefit_statistics': 'Detailed Statistics',
      'premium_benefit_premium_brushes': 'Premium Brushes',
      'premium_benefit_one_time_support': 'One-Time Support',
      'premium_benefit_unlimited': 'Unlimited Drawing',
      'premium_owned': 'You Own Premium',
      'premium_support_large_desc': 'Give strong support.',
      'premium_support_large_title': 'Large Support',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'Remove ads and support updates.',
      'premium_support_medium_title': 'Medium Support',
      'premium_support_small_desc': 'Keep the canvas clean.',
      'premium_support_small_title': 'Small Support',
      'premium_support_title': 'Support the app',
      'premium_plan_title': 'Support Options',
      'premium_purchase': 'Support now',
      'premium_purchase_note': 'One-time support removes ads.',
      'premium_ready': 'Premium is ready.',
      'premium_restore': 'Restore purchases',
      'premium_subtitle': 'Remove ads and support updates.',
      'premium_title': 'Premium',
      'purchase_error': "We couldn't complete your purchase.",
      'purchase_failed': "We couldn't complete your purchase.",
      'purchase_success': 'Purchase complete.',
      'purchase_unavailable': "Purchases aren't available right now.",
      'redo': 'Redo',
      'rate_app': 'Rate this App',
      'rate_app_desc': 'Leave a review on the store',
      'restore_error': "We couldn't restore your purchase yet.",
      'settings': 'Settings',
      'share': 'Share',
      'show_brush_guide': 'Show Brush Guide',
      'show_brush_guide_desc': 'Show hints below the toolbar',
      'start_drawing': 'Start Drawing',
      'undo': 'Undo',
      'more_apps': 'See More Apps',
      'more_apps_desc': 'Explore more apps',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_desc': 'View data and permission use.',
      'link_open_error': "We couldn't open this link.",
      'canvas_empty': 'Canvas is empty. Draw first.',
      'share_error': "We couldn't share your drawing.",
      'watercolor_brush': 'Watercolor Brush',
      'airbrush_brush': 'Airbrush',
      'brush_unlock_message': 'Watch a short ad to unlock this brush.',
      'brush_unlocked': 'Brush Unlocked!',
      'brush_unlock_pending_title': 'Ad is loading',
      'brush_unlock_pending_desc': 'Please try again in a moment.',
      'watch_ad': 'Watch Ad',
    },
    'ko': {
      'app_name': '간단 그림판',
      'app_subtitle': '가볍게 그리고 바로 공유해요',
      'ask_before_clear': '지우기 전 확인',
      'ask_before_clear_desc': '모든 선을 지우기 전에 한 번 더 확인해요',
      'back': '뒤로',
      'brush_guide_desc': '아래에서 브러시를 바꾸고 슬라이더로 굵기를 조절해요',
      'cancel': '취소',
      'clear': '지우기',
      'clear_canvas': '캔버스 지우기',
      'clear_canvas_confirm': '캔버스를 모두 지울까요?',
      'clear_data': '로컬 데이터 지우기',
      'clear_data_complete': '로컬 데이터를 지웠어요.',
      'clear_data_confirm': '로컬 설정과 사용 기록을 지울까요?',
      'clear_data_desc': '앱 설정과 사용 기록을 지워요',
      'confirm': '확인',
      'pick_color': '색상 선택',
      'canvas_color': '캔버스 색상',
      'canvas_color_desc': '배경 색을 선택하세요',
      'data_and_support': '데이터와 지원',
      'drawing_settings': '그리기 설정',
      'eraser_mode': '지우개 모드',
      'error': '오류',
      'exit': '종료',
      'exit_app_message': '저장한 그림은 이 기기에 남아 있어요.',
      'exit_confirmation': '앱을 종료할까요?',
      'feature_colors': '다양한 색상',
      'feature_eraser': '지우개',
      'feature_marker': '마커',
      'feature_pen': '펜',
      'feature_share': '공유하기',
      'feature_undo': '실행 취소',
      'feedback': '피드백 보내기',
      'feedback_desc': '의견을 보내주세요',
      'feedback_email_subject': '앱 피드백',
      'haptic_feedback': '진동 피드백',
      'haptic_feedback_desc': '도구 사용 시 진동',
      'language': '언어',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_statistics': '상세 통계',
      'premium_benefit_premium_brushes': '프리미엄 브러시',
      'premium_benefit_one_time_support': '1회 후원',
      'premium_benefit_unlimited': '무제한 그리기',
      'premium_owned': '프리미엄 사용 중',
      'premium_support_large_desc': '크게 후원해요.',
      'premium_support_large_title': '큰 후원',
      'premium_support_medium_badge': '인기',
      'premium_support_medium_desc': '광고 제거와 후원을 함께.',
      'premium_support_medium_title': '중간 후원',
      'premium_support_small_desc': '깨끗한 화면을 응원해요.',
      'premium_support_small_title': '작은 후원',
      'premium_support_title': '앱 후원',
      'premium_plan_title': '후원 선택',
      'premium_purchase': '후원하기',
      'premium_purchase_note': '1회 후원으로 광고 제거',
      'premium_ready': '프리미엄 사용 가능',
      'premium_restore': '구매 내역 복원',
      'premium_subtitle': '광고 제거와 업데이트 후원',
      'premium_title': '프리미엄',
      'purchase_error': '구매를 완료하지 못했어요.',
      'purchase_failed': '구매를 완료하지 못했어요.',
      'purchase_success': '구매를 완료했어요.',
      'purchase_unavailable': '지금은 구매할 수 없어요.',
      'redo': '다시 실행',
      'rate_app': '앱 평가하기',
      'rate_app_desc': '스토어에 리뷰를 남겨주세요',
      'restore_error': '구매 내역을 복원하지 못했어요.',
      'settings': '설정',
      'share': '공유하기',
      'show_brush_guide': '브러시 가이드 표시',
      'show_brush_guide_desc': '도구 막대 아래 힌트 표시',
      'start_drawing': '그리기 시작',
      'undo': '실행 취소',
      'more_apps': '다른 앱 보기',
      'more_apps_desc': '다른 앱도 볼 수 있어요',
      'privacy_policy': '개인정보 처리방침',
      'privacy_policy_desc': '데이터와 권한 처리 방식 보기',
      'link_open_error': '링크를 열지 못했어요.',
      'canvas_empty': '캔버스가 비어 있어요.',
      'share_error': '그림을 공유하지 못했어요.',
      'watercolor_brush': '수채화 브러시',
      'airbrush_brush': '에어브러시',
      'brush_unlock_message': '짧은 광고를 보면 해제돼요.',
      'brush_unlocked': '브러시 잠금 해제!',
      'brush_unlock_pending_title': '광고를 준비 중이에요',
      'brush_unlock_pending_desc': '잠시 후 다시 시도해 주세요.',
      'watch_ad': '광고 보기',
    },
    'ja': {
      'app_name': 'かんたんお絵かき',
      'app_subtitle': '自由に描いてすぐ共有',
      'ask_before_clear': '消去前に確認',
      'ask_before_clear_desc': 'すべての線を消す前に確認します',
      'back': '戻る',
      'brush_guide_desc': '下でブラシを選び、スライダーで太さを調整',
      'cancel': 'キャンセル',
      'clear': '消去',
      'clear_canvas': 'キャンバスを消去',
      'clear_canvas_confirm': 'キャンバスをすべて消去しますか？',
      'clear_data': 'ローカルデータを消去',
      'clear_data_complete': 'ローカルデータを消去しました。',
      'clear_data_confirm': '設定と履歴を消去しますか？',
      'clear_data_desc': '設定と使用履歴をリセット',
      'confirm': '確認',
      'pick_color': '色を選択',
      'canvas_color': 'キャンバスの色',
      'canvas_color_desc': 'キャンバスの背景色を選んでください',
      'data_and_support': 'データとサポート',
      'drawing_settings': '描画設定',
      'eraser_mode': '消しゴムモード',
      'error': 'エラー',
      'exit': '終了',
      'exit_app_message': '保存した絵はこの端末に残ります。',
      'exit_confirmation': 'アプリを終了しますか？',
      'feature_colors': '多彩な色',
      'feature_eraser': '消しゴム',
      'feature_marker': 'マーカー',
      'feature_pen': 'ペン',
      'feature_share': '共有',
      'feature_undo': '元に戻す',
      'feedback': 'フィードバック',
      'feedback_desc': '改善のご意見をお送りください',
      'feedback_email_subject': 'アプリ フィードバック',
      'haptic_feedback': '触覚フィードバック',
      'haptic_feedback_desc': 'ツール操作時に振動します',
      'language': '言語',
      'premium_benefit_remove_ads': '広告を削除',
      'premium_benefit_statistics': '詳細な統計',
      'premium_benefit_premium_brushes': 'プレミアムブラシ',
      'premium_benefit_one_time_support': '1回限りの応援',
      'premium_benefit_unlimited': '無制限に描画',
      'premium_owned': 'プレミアム利用中',
      'premium_support_large_desc': '大きく応援。',
      'premium_support_large_title': '大きく応援',
      'premium_support_medium_badge': '人気',
      'premium_support_medium_desc': '広告削除と応援にちょうどいい。',
      'premium_support_medium_title': 'ふつうに応援',
      'premium_support_small_desc': 'きれいなキャンバスを少し応援。',
      'premium_support_small_title': '少し応援',
      'premium_support_title': 'アプリを応援',
      'premium_plan_title': '応援を選択',
      'premium_purchase': '応援する',
      'premium_purchase_note': '一度の応援で広告が消えます。',
      'premium_ready': 'プレミアムを利用できます。',
      'premium_restore': '購入を復元',
      'premium_subtitle': '広告を消して今後の更新を応援。',
      'premium_title': 'プレミアム',
      'purchase_error': '購入を完了できませんでした。',
      'purchase_failed': '購入を完了できませんでした。',
      'purchase_success': '購入が完了しました。',
      'purchase_unavailable': '現在購入できません。',
      'redo': 'やり直す',
      'rate_app': 'アプリを評価',
      'rate_app_desc': 'ストアにレビューを投稿',
      'restore_error': '購入を復元できませんでした。',
      'settings': '設定',
      'share': '共有',
      'show_brush_guide': 'ブラシガイドを表示',
      'show_brush_guide_desc': '描画ツールバー下にヒントを表示',
      'start_drawing': '描き始める',
      'undo': '元に戻す',
      'more_apps': '他のアプリ',
      'more_apps_desc': '他のアプリを見る',
      'privacy_policy': 'プライバシーポリシー',
      'privacy_policy_desc': 'データと権限の扱いを確認',
      'link_open_error': 'リンクを開けませんでした。',
      'canvas_empty': 'キャンバスが空です。描いてみましょう。',
      'share_error': '絵を共有できませんでした。',
      'watercolor_brush': '水彩ブラシ',
      'airbrush_brush': 'エアブラシ',
      'brush_unlock_message': '短い広告で解除できます。',
      'brush_unlocked': 'ブラシを解除しました',
      'brush_unlock_pending_title': '広告を準備中です',
      'brush_unlock_pending_desc': 'しばらくしてからもう一度お試しください。',
      'watch_ad': '広告を見る',
    },
    'de': {
      'app_name': 'Zeichenblock',
      'app_subtitle': 'Frei zeichnen und teilen',
      'ask_before_clear': 'Vor dem Löschen fragen',
      'ask_before_clear_desc': 'Vor dem Entfernen aller Striche bestätigen',
      'back': 'Zurück',
      'brush_guide_desc': 'Pinsel unten wählen und Größe per Regler ändern',
      'cancel': 'Abbrechen',
      'clear': 'Löschen',
      'clear_canvas': 'Leinwand löschen',
      'clear_canvas_confirm': 'Alles auf der Leinwand löschen?',
      'clear_data': 'Lokale Daten löschen',
      'clear_data_complete': 'Lokale Daten wurden gelöscht.',
      'clear_data_confirm': 'Einstellungen und Verlauf löschen?',
      'clear_data_desc': 'Einstellungen und Verlauf zurücksetzen',
      'confirm': 'Bestätigen',
      'pick_color': 'Farbe wählen',
      'canvas_color': 'Leinwandfarbe',
      'canvas_color_desc': 'Wählen Sie eine Hintergrundfarbe für die Leinwand',
      'data_and_support': 'Daten & Support',
      'drawing_settings': 'Zeicheneinstellungen',
      'eraser_mode': 'Radiermodus',
      'error': 'Fehler',
      'exit': 'Beenden',
      'exit_app_message': 'Gespeicherte Zeichnungen bleiben auf diesem Gerät.',
      'exit_confirmation': 'App beenden?',
      'feature_colors': 'Viele Farben',
      'feature_eraser': 'Radierer',
      'feature_marker': 'Marker',
      'feature_pen': 'Stift',
      'feature_share': 'Teilen',
      'feature_undo': 'Rückgängig',
      'feedback': 'Feedback senden',
      'feedback_desc': 'Feedback teilen',
      'feedback_email_subject': 'App-Feedback',
      'haptic_feedback': 'Haptisches Feedback',
      'haptic_feedback_desc': 'Vibrieren bei Werkzeugaktionen',
      'language': 'Sprache',
      'premium_benefit_remove_ads': 'Werbung entfernen',
      'premium_benefit_statistics': 'Detaillierte Statistik',
      'premium_benefit_premium_brushes': 'Premium-Pinsel',
      'premium_benefit_one_time_support': 'Einmalige Unterstützung',
      'premium_benefit_unlimited': 'Unbegrenzt zeichnen',
      'premium_owned': 'Premium ist aktiv',
      'premium_support_large_desc': 'Starke Unterstützung.',
      'premium_support_large_title': 'Große Unterstützung',
      'premium_support_medium_badge': 'Beliebt',
      'premium_support_medium_desc': 'Werbung entfernen und helfen.',
      'premium_support_medium_title': 'Mittlere Unterstützung',
      'premium_support_small_desc': 'Für eine saubere Leinwand.',
      'premium_support_small_title': 'Kleine Unterstützung',
      'premium_support_title': 'App unterstützen',
      'premium_plan_title': 'Unterstützung wählen',
      'premium_purchase': 'Jetzt unterstützen',
      'premium_purchase_note': 'Einmalig unterstützen, Werbung entfernen.',
      'premium_ready': 'Premium ist bereit.',
      'premium_restore': 'Käufe wiederherstellen',
      'premium_subtitle': 'Werbung entfernen und Updates unterstützen.',
      'premium_title': 'Premium',
      'purchase_error': 'Der Kauf konnte nicht abgeschlossen werden.',
      'purchase_failed': 'Der Kauf konnte nicht abgeschlossen werden.',
      'purchase_success': 'Kauf abgeschlossen.',
      'purchase_unavailable': 'Käufe sind gerade nicht verfügbar.',
      'redo': 'Wiederholen',
      'rate_app': 'App bewerten',
      'rate_app_desc': 'Bewertung im Store hinterlassen',
      'restore_error': 'Kauf konnte nicht wiederhergestellt werden.',
      'settings': 'Einstellungen',
      'share': 'Teilen',
      'show_brush_guide': 'Pinselhilfe anzeigen',
      'show_brush_guide_desc': 'Hinweis unter der Werkzeugleiste anzeigen',
      'start_drawing': 'Zeichnen starten',
      'undo': 'Rückgängig',
      'more_apps': 'Weitere Apps',
      'more_apps_desc': 'Weitere Apps ansehen',
      'privacy_policy': 'Datenschutz',
      'privacy_policy_desc': 'Umgang mit Daten und Berechtigungen ansehen',
      'link_open_error': 'Link konnte nicht geöffnet werden.',
      'canvas_empty': 'Leinwand ist leer. Beginne zu zeichnen.',
      'share_error': 'Zeichnung konnte nicht geteilt werden.',
      'watercolor_brush': 'Aquarellpinsel',
      'airbrush_brush': 'Airbrush',
      'brush_unlock_message': 'Kurze Anzeige ansehen und Pinsel freischalten.',
      'brush_unlocked': 'Pinsel freigeschaltet',
      'brush_unlock_pending_title': 'Anzeige wird geladen',
      'brush_unlock_pending_desc': 'Bitte versuchen Sie es gleich erneut.',
      'watch_ad': 'Anzeige ansehen',
    },
    'ru': {
      'app_name': 'Рисуй легко',
      'app_subtitle': 'Рисуйте свободно и делитесь',
      'ask_before_clear': 'Подтверждать очистку',
      'ask_before_clear_desc': 'Спрашивать перед удалением всех штрихов',
      'back': 'Назад',
      'brush_guide_desc': 'Выберите кисть ниже и настройте размер',
      'cancel': 'Отмена',
      'clear': 'Очистить',
      'clear_canvas': 'Очистить холст',
      'clear_canvas_confirm': 'Очистить весь холст?',
      'clear_data': 'Очистить данные',
      'clear_data_complete': 'Локальные данные очищены.',
      'clear_data_confirm': 'Очистить настройки и историю?',
      'clear_data_desc': 'Сбросить настройки и историю',
      'confirm': 'Подтвердить',
      'pick_color': 'Выбрать цвет',
      'canvas_color': 'Цвет холста',
      'canvas_color_desc': 'Выберите цвет фона холста',
      'data_and_support': 'Данные и поддержка',
      'drawing_settings': 'Настройки рисования',
      'eraser_mode': 'Режим ластика',
      'error': 'Ошибка',
      'exit': 'Выйти',
      'exit_app_message': 'Сохранённые рисунки останутся на устройстве.',
      'exit_confirmation': 'Выйти из приложения?',
      'feature_colors': 'Много цветов',
      'feature_eraser': 'Ластик',
      'feature_marker': 'Маркер',
      'feature_pen': 'Перо',
      'feature_share': 'Поделиться',
      'feature_undo': 'Отмена',
      'feedback': 'Отправить отзыв',
      'feedback_desc': 'Поделитесь идеями по улучшению',
      'feedback_email_subject': 'Отзыв о приложении',
      'haptic_feedback': 'Виброотклик',
      'haptic_feedback_desc': 'Вибрация при использовании инструментов',
      'language': 'Язык',
      'premium_benefit_remove_ads': 'Без рекламы',
      'premium_benefit_statistics': 'Подробная статистика',
      'premium_benefit_premium_brushes': 'Премиум-кисти',
      'premium_benefit_one_time_support': 'Разовая поддержка',
      'premium_benefit_unlimited': 'Рисование без ограничений',
      'premium_owned': 'Premium активен',
      'premium_support_large_desc': 'Большая поддержка приложения.',
      'premium_support_large_title': 'Большая поддержка',
      'premium_support_medium_badge': 'Популярно',
      'premium_support_medium_desc': 'Убрать рекламу и поддержать проект.',
      'premium_support_medium_title': 'Средняя поддержка',
      'premium_support_small_desc': 'Небольшое спасибо за чистый холст.',
      'premium_support_small_title': 'Малая поддержка',
      'premium_support_title': 'Поддержать приложение',
      'premium_plan_title': 'Варианты поддержки',
      'premium_purchase': 'Поддержать',
      'premium_purchase_note': 'Разовая поддержка. Реклама будет удалена.',
      'premium_ready': 'Premium готов.',
      'premium_restore': 'Восстановить покупки',
      'premium_subtitle': 'Уберите рекламу и поддержите обновления.',
      'premium_title': 'Premium',
      'purchase_error': 'Не удалось завершить покупку.',
      'purchase_failed': 'Не удалось завершить покупку.',
      'purchase_success': 'Покупка завершена.',
      'purchase_unavailable': 'Покупки сейчас недоступны.',
      'redo': 'Повторить',
      'rate_app': 'Оценить приложение',
      'rate_app_desc': 'Оставьте отзыв в магазине',
      'restore_error': 'Не удалось восстановить покупку.',
      'settings': 'Настройки',
      'share': 'Поделиться',
      'show_brush_guide': 'Показать подсказку кистей',
      'show_brush_guide_desc': 'Показывать подсказку под панелью рисования',
      'start_drawing': 'Начать рисовать',
      'undo': 'Отменить',
      'more_apps': 'Другие приложения',
      'more_apps_desc': 'Посмотреть другие приложения',
      'privacy_policy': 'Политика конфиденциальности',
      'privacy_policy_desc': 'Как используются данные и разрешения',
      'link_open_error': 'Не удалось открыть ссылку.',
      'canvas_empty': 'Холст пуст. Начните рисовать.',
      'share_error': 'Не удалось поделиться рисунком.',
      'watercolor_brush': 'Акварельная кисть',
      'airbrush_brush': 'Аэрограф',
      'brush_unlock_message':
          'Посмотрите короткую рекламу, чтобы открыть кисть.',
      'brush_unlocked': 'Кисть открыта',
      'brush_unlock_pending_title': 'Реклама загружается',
      'brush_unlock_pending_desc': 'Попробуйте через несколько секунд.',
      'watch_ad': 'Смотреть рекламу',
    },
    'fr': {
      'app_name': 'Bloc dessin',
      'app_subtitle': 'Dessinez librement et partagez',
      'ask_before_clear': 'Confirmer avant d’effacer',
      'ask_before_clear_desc': 'Demander avant de supprimer tous les traits',
      'back': 'Retour',
      'brush_guide_desc': 'Choisissez un pinceau et réglez la taille',
      'cancel': 'Annuler',
      'clear': 'Effacer',
      'clear_canvas': 'Effacer la toile',
      'clear_canvas_confirm': 'Effacer tout le contenu ?',
      'clear_data': 'Effacer les données',
      'clear_data_complete': 'Données locales effacées.',
      'clear_data_confirm': 'Effacer les réglages et l’historique ?',
      'clear_data_desc': 'Réinitialiser les réglages et l’historique',
      'confirm': 'Confirmer',
      'pick_color': 'Choisir une couleur',
      'canvas_color': 'Couleur du canevas',
      'canvas_color_desc': 'Choisissez une couleur de fond pour le canevas',
      'data_and_support': 'Données et support',
      'drawing_settings': 'Réglages de dessin',
      'eraser_mode': 'Mode gomme',
      'error': 'Erreur',
      'exit': 'Quitter',
      'exit_app_message': 'Vos dessins enregistrés restent sur cet appareil.',
      'exit_confirmation': 'Quitter l’appli ?',
      'feature_colors': 'Nombreuses couleurs',
      'feature_eraser': 'Gomme',
      'feature_marker': 'Marqueur',
      'feature_pen': 'Stylo',
      'feature_share': 'Partager',
      'feature_undo': 'Annuler',
      'feedback': 'Envoyer un avis',
      'feedback_desc': 'Partagez vos idées d’amélioration',
      'feedback_email_subject': 'Avis sur l’app',
      'haptic_feedback': 'Retour haptique',
      'haptic_feedback_desc': 'Vibrer lors de l’utilisation des outils',
      'language': 'Langue',
      'premium_benefit_remove_ads': 'Supprimer les pubs',
      'premium_benefit_statistics': 'Statistiques détaillées',
      'premium_benefit_premium_brushes': 'Pinceaux premium',
      'premium_benefit_one_time_support': 'Soutien unique',
      'premium_benefit_unlimited': 'Dessin illimité',
      'premium_owned': 'Premium activé',
      'premium_support_large_desc': 'Grand soutien pour l’app.',
      'premium_support_large_title': 'Grand soutien',
      'premium_support_medium_badge': 'Populaire',
      'premium_support_medium_desc': 'Supprime les pubs et aide le projet.',
      'premium_support_medium_title': 'Soutien moyen',
      'premium_support_small_desc': 'Un petit merci pour une toile propre.',
      'premium_support_small_title': 'Petit soutien',
      'premium_support_title': 'Soutenir l’app',
      'premium_plan_title': 'Choisir un soutien',
      'premium_purchase': 'Soutenir',
      'premium_purchase_note': 'Soutien unique. Les pubs restent supprimées.',
      'premium_ready': 'Premium est prêt.',
      'premium_restore': 'Restaurer les achats',
      'premium_subtitle': 'Supprimez les pubs et soutenez les mises à jour.',
      'premium_title': 'Premium',
      'purchase_error': 'Achat impossible.',
      'purchase_failed': 'Achat impossible.',
      'purchase_success': 'Achat terminé.',
      'purchase_unavailable': 'Achats indisponibles pour le moment.',
      'redo': 'Rétablir',
      'rate_app': 'Noter l’application',
      'rate_app_desc': 'Laisser un avis sur le store',
      'restore_error': 'Restauration impossible.',
      'settings': 'Réglages',
      'share': 'Partager',
      'show_brush_guide': 'Afficher le guide',
      'show_brush_guide_desc': 'Afficher l’aide sous la barre de dessin',
      'start_drawing': 'Commencer à dessiner',
      'undo': 'Annuler',
      'more_apps': 'Autres apps',
      'more_apps_desc': 'Voir d’autres apps',
      'privacy_policy': 'Confidentialité',
      'privacy_policy_desc': 'Voir l’usage des données et permissions',
      'link_open_error': 'Impossible d’ouvrir ce lien.',
      'canvas_empty': 'La toile est vide. Commencez à dessiner.',
      'share_error': 'Impossible de partager le dessin.',
      'watercolor_brush': 'Pinceau aquarelle',
      'airbrush_brush': 'Aérographe',
      'brush_unlock_message':
          'Regardez une courte pub pour débloquer ce pinceau.',
      'brush_unlocked': 'Pinceau débloqué',
      'brush_unlock_pending_title': 'L’annonce charge',
      'brush_unlock_pending_desc': 'Veuillez réessayer dans un instant.',
      'watch_ad': 'Voir la pub',
    },
    'es': {
      'app_name': 'Dibujo Fácil',
      'app_subtitle': 'Dibuja libremente y comparte',
      'ask_before_clear': 'Confirmar antes de borrar',
      'ask_before_clear_desc': 'Pedir confirmación antes de borrar todo',
      'back': 'Atrás',
      'brush_guide_desc': 'Elige un pincel abajo y ajusta el tamaño',
      'cancel': 'Cancelar',
      'clear': 'Borrar',
      'clear_canvas': 'Borrar lienzo',
      'clear_canvas_confirm': '¿Borrar todo el lienzo?',
      'clear_data': 'Borrar datos locales',
      'clear_data_complete': 'Datos locales borrados.',
      'clear_data_confirm': '¿Borrar ajustes e historial?',
      'clear_data_desc': 'Restablecer ajustes e historial',
      'confirm': 'Confirmar',
      'pick_color': 'Elegir color',
      'canvas_color': 'Color del lienzo',
      'canvas_color_desc': 'Elige un color de fondo para el lienzo',
      'data_and_support': 'Datos y soporte',
      'drawing_settings': 'Ajustes de dibujo',
      'eraser_mode': 'Modo borrador',
      'error': 'Error',
      'exit': 'Salir',
      'exit_app_message': 'Tus dibujos guardados quedan en este dispositivo.',
      'exit_confirmation': '¿Salir de la app?',
      'feature_colors': 'Muchos colores',
      'feature_eraser': 'Borrador',
      'feature_marker': 'Marcador',
      'feature_pen': 'Lápiz',
      'feature_share': 'Compartir',
      'feature_undo': 'Deshacer',
      'feedback': 'Enviar comentarios',
      'feedback_desc': 'Comparte ideas para mejorar la app',
      'feedback_email_subject': 'Comentarios de la app',
      'haptic_feedback': 'Respuesta háptica',
      'haptic_feedback_desc': 'Vibrar al usar herramientas',
      'language': 'Idioma',
      'premium_benefit_remove_ads': 'Quitar anuncios',
      'premium_benefit_statistics': 'Estadísticas detalladas',
      'premium_benefit_premium_brushes': 'Pinceles premium',
      'premium_benefit_one_time_support': 'Apoyo único',
      'premium_benefit_unlimited': 'Dibujo ilimitado',
      'premium_owned': 'Tienes Premium',
      'premium_support_large_desc': 'Da un apoyo grande.',
      'premium_support_large_title': 'Apoyo grande',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'Quita anuncios y ayuda al proyecto.',
      'premium_support_medium_title': 'Apoyo medio',
      'premium_support_small_desc': 'Un pequeño gracias por un lienzo limpio.',
      'premium_support_small_title': 'Apoyo pequeño',
      'premium_support_title': 'Apoyar la app',
      'premium_plan_title': 'Elige apoyo',
      'premium_purchase': 'Apoyar ahora',
      'premium_purchase_note': 'Apoyo único. Los anuncios quedan fuera.',
      'premium_ready': 'Premium está listo.',
      'premium_restore': 'Restaurar compras',
      'premium_subtitle': 'Quita anuncios y apoya futuras mejoras.',
      'premium_title': 'Premium',
      'purchase_error': 'No se pudo completar la compra.',
      'purchase_failed': 'No se pudo completar la compra.',
      'purchase_success': 'Compra completada.',
      'purchase_unavailable': 'Las compras no están disponibles ahora.',
      'redo': 'Rehacer',
      'rate_app': 'Calificar la app',
      'rate_app_desc': 'Deja una reseña en la tienda',
      'restore_error': 'No se pudo restaurar la compra.',
      'settings': 'Ajustes',
      'share': 'Compartir',
      'show_brush_guide': 'Mostrar guía de pinceles',
      'show_brush_guide_desc': 'Mostrar la ayuda bajo la barra de dibujo',
      'start_drawing': 'Empezar a dibujar',
      'undo': 'Deshacer',
      'more_apps': 'Más apps',
      'more_apps_desc': 'Explora más apps',
      'privacy_policy': 'Privacidad',
      'privacy_policy_desc': 'Ver cómo se usan datos y permisos',
      'link_open_error': 'No se pudo abrir el enlace.',
      'canvas_empty': 'El lienzo está vacío. Empieza a dibujar.',
      'share_error': 'No se pudo compartir el dibujo.',
      'watercolor_brush': 'Pincel de acuarela',
      'airbrush_brush': 'Aerógrafo',
      'brush_unlock_message':
          'Mira un anuncio corto para desbloquear este pincel.',
      'brush_unlocked': 'Pincel desbloqueado',
      'brush_unlock_pending_title': 'El anuncio se está cargando',
      'brush_unlock_pending_desc': 'Vuelve a intentarlo en un momento.',
      'watch_ad': 'Ver anuncio',
    },
    'pt': {
      'app_name': 'Tela Fácil',
      'app_subtitle': 'Desenhe livremente e compartilhe',
      'ask_before_clear': 'Confirmar antes de limpar',
      'ask_before_clear_desc': 'Pedir confirmação antes de apagar tudo',
      'back': 'Voltar',
      'brush_guide_desc': 'Escolha um pincel abaixo e ajuste o tamanho',
      'cancel': 'Cancelar',
      'clear': 'Limpar',
      'clear_canvas': 'Limpar tela',
      'clear_canvas_confirm': 'Limpar todo o conteúdo da tela?',
      'clear_data': 'Limpar dados locais',
      'clear_data_complete': 'Dados locais limpos.',
      'clear_data_confirm': 'Limpar configurações e histórico?',
      'clear_data_desc': 'Redefinir configurações e histórico',
      'confirm': 'Confirmar',
      'pick_color': 'Escolher cor',
      'canvas_color': 'Cor da tela',
      'canvas_color_desc': 'Escolha uma cor de fundo para a tela',
      'data_and_support': 'Dados e suporte',
      'drawing_settings': 'Configurações de desenho',
      'eraser_mode': 'Modo borracha',
      'error': 'Erro',
      'exit': 'Sair',
      'exit_app_message': 'Seus desenhos salvos ficam neste aparelho.',
      'exit_confirmation': 'Sair do app?',
      'feature_colors': 'Várias cores',
      'feature_eraser': 'Borracha',
      'feature_marker': 'Marcador',
      'feature_pen': 'Caneta',
      'feature_share': 'Compartilhar',
      'feature_undo': 'Desfazer',
      'feedback': 'Enviar feedback',
      'feedback_desc': 'Compartilhe ideias para melhorar o app',
      'feedback_email_subject': 'Feedback do app',
      'haptic_feedback': 'Feedback tátil',
      'haptic_feedback_desc': 'Vibrar ao usar ferramentas',
      'language': 'Idioma',
      'premium_benefit_remove_ads': 'Remover anúncios',
      'premium_benefit_statistics': 'Estatísticas detalhadas',
      'premium_benefit_premium_brushes': 'Pincéis premium',
      'premium_benefit_one_time_support': 'Apoio único',
      'premium_benefit_unlimited': 'Desenho ilimitado',
      'premium_owned': 'Premium ativo',
      'premium_support_large_desc': 'Dê um apoio forte.',
      'premium_support_large_title': 'Apoio grande',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'Remove anúncios e ajuda o projeto.',
      'premium_support_medium_title': 'Apoio médio',
      'premium_support_small_desc': 'Um pequeno obrigado por uma tela limpa.',
      'premium_support_small_title': 'Apoio pequeno',
      'premium_support_title': 'Apoiar o app',
      'premium_plan_title': 'Escolha o apoio',
      'premium_purchase': 'Apoiar agora',
      'premium_purchase_note': 'Apoio único. Os anúncios ficam removidos.',
      'premium_ready': 'Premium pronto.',
      'premium_restore': 'Restaurar compras',
      'premium_subtitle': 'Remova anúncios e apoie futuras atualizações.',
      'premium_title': 'Premium',
      'purchase_error': 'Não foi possível concluir a compra.',
      'purchase_failed': 'Não foi possível concluir a compra.',
      'purchase_success': 'Compra concluída.',
      'purchase_unavailable': 'Compras indisponíveis no momento.',
      'redo': 'Refazer',
      'rate_app': 'Avaliar app',
      'rate_app_desc': 'Deixe uma avaliação na loja',
      'restore_error': 'Não foi possível restaurar a compra.',
      'settings': 'Configurações',
      'share': 'Compartilhar',
      'show_brush_guide': 'Mostrar guia de pincéis',
      'show_brush_guide_desc': 'Mostrar dica abaixo da barra de desenho',
      'start_drawing': 'Começar a desenhar',
      'undo': 'Desfazer',
      'more_apps': 'Mais apps',
      'more_apps_desc': 'Veja mais apps',
      'privacy_policy': 'Privacidade',
      'privacy_policy_desc': 'Veja como dados e permissões são usados',
      'link_open_error': 'Não foi possível abrir o link.',
      'canvas_empty': 'A tela está vazia. Comece a desenhar.',
      'share_error': 'Não foi possível compartilhar o desenho.',
      'watercolor_brush': 'Pincel aquarela',
      'airbrush_brush': 'Aerógrafo',
      'brush_unlock_message':
          'Veja um anúncio curto para desbloquear este pincel.',
      'brush_unlocked': 'Pincel desbloqueado',
      'brush_unlock_pending_title': 'O anúncio está carregando',
      'brush_unlock_pending_desc': 'Tente novamente em instantes.',
      'watch_ad': 'Ver anúncio',
    },
    'id': {
      'app_name': 'Gambar Mudah',
      'app_subtitle': 'Gambar bebas dan bagikan',
      'ask_before_clear': 'Konfirmasi sebelum hapus',
      'ask_before_clear_desc': 'Minta konfirmasi sebelum menghapus semua garis',
      'back': 'Kembali',
      'brush_guide_desc': 'Pilih kuas di bawah dan atur ukurannya',
      'cancel': 'Batal',
      'clear': 'Hapus',
      'clear_canvas': 'Hapus kanvas',
      'clear_canvas_confirm': 'Hapus semua isi kanvas?',
      'clear_data': 'Hapus data lokal',
      'clear_data_complete': 'Data lokal dihapus.',
      'clear_data_confirm': 'Hapus pengaturan dan riwayat?',
      'clear_data_desc': 'Reset pengaturan dan riwayat',
      'confirm': 'Konfirmasi',
      'pick_color': 'Pilih warna',
      'canvas_color': 'Warna kanvas',
      'canvas_color_desc': 'Pilih warna latar kanvas',
      'data_and_support': 'Data & dukungan',
      'drawing_settings': 'Pengaturan gambar',
      'eraser_mode': 'Mode penghapus',
      'error': 'Error',
      'exit': 'Keluar',
      'exit_app_message': 'Gambar tersimpan tetap di perangkat ini.',
      'exit_confirmation': 'Keluar dari aplikasi?',
      'feature_colors': 'Banyak warna',
      'feature_eraser': 'Penghapus',
      'feature_marker': 'Marker',
      'feature_pen': 'Pena',
      'feature_share': 'Bagikan',
      'feature_undo': 'Urungkan',
      'feedback': 'Kirim masukan',
      'feedback_desc': 'Bagikan ide untuk meningkatkan aplikasi',
      'feedback_email_subject': 'Masukan aplikasi',
      'haptic_feedback': 'Umpan balik getar',
      'haptic_feedback_desc': 'Getar saat memakai alat gambar',
      'language': 'Bahasa',
      'premium_benefit_remove_ads': 'Hapus iklan',
      'premium_benefit_statistics': 'Statistik detail',
      'premium_benefit_premium_brushes': 'Kuas premium',
      'premium_benefit_one_time_support': 'Dukungan sekali',
      'premium_benefit_unlimited': 'Menggambar tanpa batas',
      'premium_owned': 'Premium aktif',
      'premium_support_large_desc': 'Beri dukungan besar.',
      'premium_support_large_title': 'Dukungan besar',
      'premium_support_medium_badge': 'Populer',
      'premium_support_medium_desc': 'Hapus iklan dan bantu proyek ini.',
      'premium_support_medium_title': 'Dukungan sedang',
      'premium_support_small_desc': 'Terima kasih kecil untuk kanvas bersih.',
      'premium_support_small_title': 'Dukungan kecil',
      'premium_support_title': 'Dukung aplikasi',
      'premium_plan_title': 'Pilih dukungan',
      'premium_purchase': 'Dukung sekarang',
      'premium_purchase_note': 'Dukungan sekali. Iklan tetap dihapus.',
      'premium_ready': 'Premium siap digunakan.',
      'premium_restore': 'Pulihkan pembelian',
      'premium_subtitle': 'Hapus iklan dan dukung pembaruan.',
      'premium_title': 'Premium',
      'purchase_error': 'Pembelian tidak dapat diselesaikan.',
      'purchase_failed': 'Pembelian tidak dapat diselesaikan.',
      'purchase_success': 'Pembelian selesai.',
      'purchase_unavailable': 'Pembelian belum tersedia saat ini.',
      'redo': 'Ulangi',
      'rate_app': 'Nilai aplikasi',
      'rate_app_desc': 'Tinggalkan ulasan di toko',
      'restore_error': 'Pembelian belum dapat dipulihkan.',
      'settings': 'Pengaturan',
      'share': 'Bagikan',
      'show_brush_guide': 'Tampilkan panduan kuas',
      'show_brush_guide_desc': 'Tampilkan petunjuk di bawah toolbar gambar',
      'start_drawing': 'Mulai menggambar',
      'undo': 'Urungkan',
      'more_apps': 'Aplikasi lain',
      'more_apps_desc': 'Lihat aplikasi lain',
      'privacy_policy': 'Privasi',
      'privacy_policy_desc': 'Lihat penggunaan data dan izin',
      'link_open_error': 'Tautan tidak dapat dibuka.',
      'canvas_empty': 'Kanvas kosong. Mulailah menggambar.',
      'share_error': 'Gambar tidak dapat dibagikan.',
      'watercolor_brush': 'Kuas cat air',
      'airbrush_brush': 'Airbrush',
      'brush_unlock_message': 'Tonton iklan singkat untuk membuka kuas ini.',
      'brush_unlocked': 'Kuas terbuka',
      'brush_unlock_pending_title': 'Iklan sedang dimuat',
      'brush_unlock_pending_desc': 'Coba lagi sebentar lagi.',
      'watch_ad': 'Tonton iklan',
    },
    'zh': {
      'app_name': '简易画板',
      'app_subtitle': '自由绘画，轻松分享',
      'ask_before_clear': '清空前确认',
      'ask_before_clear_desc': '清除所有笔画前先确认',
      'back': '返回',
      'brush_guide_desc': '在下方选择画笔并调整粗细',
      'cancel': '取消',
      'clear': '清除',
      'clear_canvas': '清空画布',
      'clear_canvas_confirm': '要清空整个画布吗？',
      'clear_data': '清除本地数据',
      'clear_data_complete': '本地数据已清除。',
      'clear_data_confirm': '清除设置和历史记录吗？',
      'clear_data_desc': '重置设置和历史记录',
      'confirm': '确认',
      'pick_color': '选择颜色',
      'canvas_color': '画布颜色',
      'canvas_color_desc': '选择画布的背景颜色',
      'data_and_support': '数据与支持',
      'drawing_settings': '绘画设置',
      'eraser_mode': '橡皮模式',
      'error': '错误',
      'exit': '退出',
      'exit_app_message': '已保存的画作会留在本机。',
      'exit_confirmation': '退出应用？',
      'feature_colors': '多种颜色',
      'feature_eraser': '橡皮',
      'feature_marker': '马克笔',
      'feature_pen': '画笔',
      'feature_share': '分享',
      'feature_undo': '撤销',
      'feedback': '发送反馈',
      'feedback_desc': '分享你的改进建议',
      'feedback_email_subject': '应用反馈',
      'haptic_feedback': '触觉反馈',
      'haptic_feedback_desc': '使用工具时振动',
      'language': '语言',
      'premium_benefit_remove_ads': '移除广告',
      'premium_benefit_statistics': '详细统计',
      'premium_benefit_premium_brushes': '高级画笔',
      'premium_benefit_one_time_support': '一次性支持',
      'premium_benefit_unlimited': '无限绘画',
      'premium_owned': '已开通 Premium',
      'premium_support_large_desc': '大力支持应用。',
      'premium_support_large_title': '大份支持',
      'premium_support_medium_badge': '热门',
      'premium_support_medium_desc': '移除广告并支持项目。',
      'premium_support_medium_title': '中份支持',
      'premium_support_small_desc': '为干净画布送上小小支持。',
      'premium_support_small_title': '小份支持',
      'premium_support_title': '支持应用',
      'premium_plan_title': '选择支持',
      'premium_purchase': '立即支持',
      'premium_purchase_note': '一次支持，广告持续移除。',
      'premium_ready': 'Premium 已可使用。',
      'premium_restore': '恢复购买',
      'premium_subtitle': '移除广告，支持后续更新。',
      'premium_title': 'Premium',
      'purchase_error': '无法完成购买。',
      'purchase_failed': '无法完成购买。',
      'purchase_success': '购买完成。',
      'purchase_unavailable': '当前无法购买。',
      'redo': '重做',
      'rate_app': '评价应用',
      'rate_app_desc': '在商店留下评价',
      'restore_error': '无法恢复购买。',
      'settings': '设置',
      'share': '分享',
      'show_brush_guide': '显示画笔指南',
      'show_brush_guide_desc': '在绘画工具栏下方显示提示',
      'start_drawing': '开始绘画',
      'undo': '撤销',
      'more_apps': '更多应用',
      'more_apps_desc': '查看更多应用',
      'privacy_policy': '隐私政策',
      'privacy_policy_desc': '查看数据和权限的处理方式',
      'link_open_error': '无法打开链接。',
      'canvas_empty': '画布为空。开始绘画吧。',
      'share_error': '无法分享绘画。',
      'watercolor_brush': '水彩笔',
      'airbrush_brush': '喷枪',
      'brush_unlock_message': '观看短广告即可解锁此画笔。',
      'brush_unlocked': '画笔已解锁',
      'brush_unlock_pending_title': '广告加载中',
      'brush_unlock_pending_desc': '请稍后再试。',
      'watch_ad': '观看广告',
    },
    'ar': {
      'app_name': 'الرسم السهل',
      'app_subtitle': 'ارسم بحرية وشارك بسهولة',
      'ask_before_clear': 'تأكيد قبل المسح',
      'ask_before_clear_desc': 'اطلب التأكيد قبل حذف كل الخطوط',
      'back': 'رجوع',
      'brush_guide_desc': 'اختر الفرشاة من الأسفل واضبط الحجم',
      'cancel': 'إلغاء',
      'clear': 'مسح',
      'clear_canvas': 'مسح اللوحة',
      'clear_canvas_confirm': 'هل تريد مسح اللوحة بالكامل؟',
      'clear_data': 'مسح البيانات المحلية',
      'clear_data_complete': 'تم مسح البيانات المحلية.',
      'clear_data_confirm': 'مسح الإعدادات والسجل؟',
      'clear_data_desc': 'إعادة ضبط الإعدادات والسجل',
      'confirm': 'تأكيد',
      'pick_color': 'اختر لونًا',
      'canvas_color': 'لون اللوحة',
      'canvas_color_desc': 'اختر لون خلفية اللوحة',
      'data_and_support': 'البيانات والدعم',
      'drawing_settings': 'إعدادات الرسم',
      'eraser_mode': 'وضع الممحاة',
      'error': 'خطأ',
      'exit': 'خروج',
      'exit_app_message': 'تبقى رسوماتك المحفوظة على هذا الجهاز.',
      'exit_confirmation': 'هل تريد الخروج؟',
      'feature_colors': 'ألوان متعددة',
      'feature_eraser': 'ممحاة',
      'feature_marker': 'قلم تحديد',
      'feature_pen': 'قلم',
      'feature_share': 'مشاركة',
      'feature_undo': 'تراجع',
      'feedback': 'إرسال ملاحظات',
      'feedback_desc': 'شارك أفكارك لتحسين التطبيق',
      'feedback_email_subject': 'ملاحظات التطبيق',
      'haptic_feedback': 'اهتزاز تفاعلي',
      'haptic_feedback_desc': 'اهتزاز عند استخدام أدوات الرسم',
      'language': 'اللغة',
      'premium_benefit_remove_ads': 'إزالة الإعلانات',
      'premium_benefit_statistics': 'إحصاءات مفصلة',
      'premium_benefit_premium_brushes': 'فرش بريميوم',
      'premium_benefit_one_time_support': 'دعم لمرة واحدة',
      'premium_benefit_unlimited': 'رسم بلا حدود',
      'premium_owned': 'Premium مفعّل',
      'premium_support_large_desc': 'دعم كبير للتطبيق.',
      'premium_support_large_title': 'دعم كبير',
      'premium_support_medium_badge': 'رائج',
      'premium_support_medium_desc': 'إزالة الإعلانات ودعم التطبيق.',
      'premium_support_medium_title': 'دعم متوسط',
      'premium_support_small_desc': 'شكر بسيط للوحة نظيفة.',
      'premium_support_small_title': 'دعم بسيط',
      'premium_support_title': 'دعم التطبيق',
      'premium_plan_title': 'اختر الدعم',
      'premium_purchase': 'ادعم الآن',
      'premium_purchase_note': 'دعم لمرة واحدة. تبقى الإعلانات محذوفة.',
      'premium_ready': 'Premium جاهز.',
      'premium_restore': 'استعادة المشتريات',
      'premium_subtitle': 'أزل الإعلانات وادعم التحديثات القادمة.',
      'premium_title': 'Premium',
      'purchase_error': 'تعذر إكمال الشراء.',
      'purchase_failed': 'تعذر إكمال الشراء.',
      'purchase_success': 'تم الشراء.',
      'purchase_unavailable': 'الشراء غير متاح الآن.',
      'redo': 'إعادة',
      'rate_app': 'تقييم التطبيق',
      'rate_app_desc': 'اترك مراجعة في المتجر',
      'restore_error': 'تعذرت استعادة الشراء.',
      'settings': 'الإعدادات',
      'share': 'مشاركة',
      'show_brush_guide': 'إظهار دليل الفرش',
      'show_brush_guide_desc': 'إظهار التلميح أسفل شريط أدوات الرسم',
      'start_drawing': 'ابدأ الرسم',
      'undo': 'تراجع',
      'more_apps': 'المزيد من التطبيقات',
      'more_apps_desc': 'استكشف تطبيقات أخرى',
      'privacy_policy': 'الخصوصية',
      'privacy_policy_desc': 'اطلع على استخدام البيانات والأذونات',
      'link_open_error': 'تعذر فتح الرابط.',
      'canvas_empty': 'اللوحة فارغة. ابدأ الرسم للمشاركة.',
      'share_error': 'تعذرت مشاركة الرسم.',
      'watercolor_brush': 'فرشاة ألوان مائية',
      'airbrush_brush': 'بخاخ',
      'brush_unlock_message': 'شاهد إعلانًا قصيرًا لفتح هذه الفرشاة.',
      'brush_unlocked': 'تم فتح الفرشاة',
      'brush_unlock_pending_title': 'يتم تحميل الإعلان',
      'brush_unlock_pending_desc': 'حاول مجددًا بعد قليل.',
      'watch_ad': 'مشاهدة إعلان',
    },
  };
}
