import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
    static const List<Locale> supportedLocales = [
    Locale('en'), // 미국 영어
    Locale('ko'), // 대한민국 한국어
    Locale('ja'), // 일본어
    Locale('de'), // 독일어
    Locale('ru'), // 러시아어
    Locale('fr'), // 프랑스어
    Locale('es'), // 스페인어
    Locale('pt'), // 포르투갈어
    Locale('id'), // 인도네시아어
    Locale('zh'), // 중국어
    Locale('ar'), // 아랍어
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Draw freely and share',
      'ask_before_clear': 'Confirm before clearing',
      'ask_before_clear_desc':
          'Ask for confirmation before erasing all strokes',
      'back': 'Back',
      'brush_guide': 'Brush Guide',
      'brush_guide_desc':
          'Change brushes below and drag the slider to adjust size',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'clear_all': 'Clear All',
      'clear_canvas': 'Clear Canvas',
      'clear_canvas_confirm': 'Clear all content on the canvas?',
      'clear_data': 'Clear Local Data',
      'clear_data_complete': 'Local data is cleared.',
      'clear_data_confirm': 'Clear local settings and activity history?',
      'clear_data_desc': 'Reset app settings and activity history',
      'confirm': 'Confirm',
      'data_and_support': 'Data & Support',
      'drawing_settings': 'Drawing Settings',
      'eraser_mode': 'Eraser Mode',
      'error': 'Error',
      'feature_colors': 'Multiple Colors',
      'feature_eraser': 'Eraser',
      'feature_marker': 'Marker',
      'feature_pen': 'Pen',
      'feature_share': 'Share',
      'feature_undo': 'Undo',
      'feedback': 'Send Feedback',
      'feedback_desc': 'Send us your thoughts to improve the app',
      'feedback_tip': 'This feature is on the way. Thanks for waiting.',
      'feedback_email_subject': 'Doodle Pad Feedback',
      'haptic_feedback': 'Haptic Feedback',
      'haptic_feedback_desc': 'Vibrate when using drawing tools',
      'history': 'History',
      'history_subtitle': '@screen / @route',
      'language': 'Language',
      'no_history': 'No history yet.',
      'open_history': 'History',
      'open_history_desc': 'View previous drawings and activity',
      'open_stats': 'Stats',
      'open_stats_desc': 'View app usage statistics and activity',
      'premium_benefit_remove_ads': 'Remove Ads',
      'premium_benefit_statistics': 'Detailed Statistics',
      'premium_benefit_unlimited': 'Unlimited Drawing',
      'premium_benefits': 'Premium Benefits',
      'premium_owned': 'You Own Premium',
      'premium_plan_monthly': 'Monthly Plan',
      'premium_plan_monthly_desc': 'Enjoy all premium features for 1 month',
      'premium_plan_title': 'Premium Plans',
      'premium_plan_weekly': 'Weekly Plan',
      'premium_plan_weekly_desc': 'Enjoy all premium features for 1 week',
      'premium_plan_yearly': 'Yearly Plan',
      'premium_plan_yearly_desc': 'Enjoy all premium features for 1 year',
      'premium_purchase': 'Purchase Premium',
      'premium_purchase_note': 'Premium benefits apply on all your devices.',
      'premium_ready': 'Premium is ready.',
      'premium_restore': 'Restore purchases',
      'premium_subtitle': 'Upgrade to premium features',
      'premium_title': 'Premium',
      'purchase_error': "We couldn't complete your purchase.",
      'purchase_failed': "We couldn't complete your purchase.",
      'purchase_success': 'Purchase complete.',
      'purchase_unavailable': "Purchases aren't available right now.",
      'quick_actions': 'Quick Actions',
      'redo': 'Redo',
      'refresh': 'Refresh',
      'rate_app': 'Rate this App',
      'rate_app_desc': 'Leave a review on the store',
      'restore_error': "We couldn't restore your purchase yet.",
      'settings': 'Settings',
      'share': 'Share',
      'show_brush_guide': 'Show Brush Guide',
      'show_brush_guide_desc':
          'Show the brush hint below the drawing toolbar',
      'start_drawing': 'Start Drawing',
      'stats': 'Statistics',
      'today_events': 'Today',
      'top_events': 'Top Activities',
      'total_events': 'Total Activities',
      'undo': 'Undo',
      'unique_routes': 'Screens Visited',
      'unique_screens': 'Unique Screens',
      'unknown_event': 'Unknown activity',
      'week_events': 'This Week',
      'more_apps': 'See More Apps',
      'more_apps_desc': 'Explore more apps from DangunDad',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_desc': 'See how local data and permissions are handled.',
      'link_open_error': "We couldn't open this link right now.",
      'save': 'Save',
      'saved': 'Saved',
      'save_canvas': 'Save Drawing',
      'save_success': 'Drawing saved.',
      'save_error': "We couldn't save your drawing.",
      'gallery': 'Gallery',
      'gallery_empty': 'No saved drawings yet',
      'gallery_subtitle': 'Load or share your saved drawings',
      'saved_drawings': 'Saved Drawings',
      'load_drawing': 'Load',
      'load_drawing_message':
          'Start a new drawing with this image for reference.',
      'load_drawing_confirm': 'Clear the current drawing and load this one?',
      'delete_drawing': 'Delete Drawing',
      'delete_drawing_complete': 'Drawing deleted.',
      'delete_drawing_confirm': 'Delete this drawing?',
      'delete_error': "We couldn't delete your drawing.",
      'share_error': "We couldn't share your drawing.",
      'watercolor_brush': 'Watercolor Brush',
      'airbrush_brush': 'Airbrush',
      'watercolor_mode': 'Watercolor Mode',
      'airbrush_mode': 'Airbrush Mode',
      'brush_unlock_message':
          'Watch a short ad to permanently unlock this brush!',
      'brush_unlocked': 'Brush Unlocked!',
      'watch_ad': 'Watch Ad',
      'nav_home': 'Home',
      'nav_gallery': 'Gallery',
      'nav_history': 'History',
      'nav_stats': 'Stats',
    },
    'ko': {
      'app_name': '두들 패드',
      'app_subtitle': '가볍게 그리고 바로 공유해요',
      'ask_before_clear': '지우기 전 확인',
      'ask_before_clear_desc': '모든 선을 지우기 전에 한 번 더 확인해요',
      'back': '뒤로',
      'brush_guide': '브러시 가이드',
      'brush_guide_desc': '아래에서 브러시를 바꾸고 슬라이더로 굵기를 조절해요',
      'cancel': '취소',
      'clear': '지우기',
      'clear_all': '모두 지우기',
      'clear_canvas': '캔버스 지우기',
      'clear_canvas_confirm': '캔버스를 모두 지울까요?',
      'clear_data': '로컬 데이터 지우기',
      'clear_data_complete': '로컬 데이터를 지웠어요.',
      'clear_data_confirm': '로컬 설정과 사용 기록을 지울까요?',
      'clear_data_desc': '앱 설정과 사용 기록을 지워요',
      'confirm': '확인',
      'data_and_support': '데이터 및 고객 지원',
      'drawing_settings': '그리기 설정',
      'eraser_mode': '지우개 모드',
      'error': '오류',
      'feature_colors': '다양한 색상',
      'feature_eraser': '지우개',
      'feature_marker': '마커',
      'feature_pen': '펜',
      'feature_share': '공유하기',
      'feature_undo': '실행 취소',
      'feedback': '피드백 보내기',
      'feedback_desc': '앱 개선을 위한 의견을 보내주세요',
      'feedback_tip': '이 기능을 준비하고 있어요. 조금만 기다려 주세요.',
      'feedback_email_subject': 'Doodle Pad 피드백',
      'haptic_feedback': '진동 피드백',
      'haptic_feedback_desc': '도구 사용 시 진동으로 반응을 줍니다',
      'history': '기록',
      'history_subtitle': '@screen / @route',
      'language': '언어',
      'no_history': '아직 기록이 없어요',
      'open_history': '기록',
      'open_history_desc': '이전 그림과 활동 내역을 볼 수 있어요',
      'open_stats': '통계',
      'open_stats_desc': '앱 사용 통계와 활동 내역을 볼 수 있어요',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_statistics': '상세 통계 확인',
      'premium_benefit_unlimited': '무제한 그리기',
      'premium_benefits': '프리미엄 혜택',
      'premium_owned': '프리미엄을 쓰고 있어요',
      'premium_plan_monthly': '월간 요금제',
      'premium_plan_monthly_desc': '1개월 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_plan_title': '프리미엄 요금제',
      'premium_plan_weekly': '주간 요금제',
      'premium_plan_weekly_desc': '1주일 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_plan_yearly': '연간 요금제',
      'premium_plan_yearly_desc': '1년 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_purchase': '프리미엄 구매',
      'premium_purchase_note': '프리미엄 구매 시 모든 기기에서 혜택이 적용됩니다.',
      'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
      'premium_restore': '구매 내역 복원',
      'premium_subtitle': '광고 없이 프리미엄 기능을 쓸 수 있어요',
      'premium_title': '프리미엄',
      'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_failed': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_success': '구매를 완료했어요.',
      'purchase_unavailable': '지금은 구매를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
      'quick_actions': '빠른 실행',
      'redo': '다시 실행',
      'refresh': '새로고침',
      'rate_app': '앱 평가하기',
      'rate_app_desc': '스토어에 리뷰를 남겨주세요',
      'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
      'settings': '설정',
      'share': '공유하기',
      'show_brush_guide': '브러시 가이드 표시',
      'show_brush_guide_desc': '그리기 도구 막대 아래에 브러시 힌트를 보여줘요',
      'start_drawing': '그리기 시작',
      'stats': '통계',
      'today_events': '오늘의 활동',
      'top_events': '주요 활동',
      'total_events': '전체 활동',
      'undo': '실행 취소',
      'unique_routes': '방문한 화면 수',
      'unique_screens': '고유 화면 수',
      'unknown_event': '알 수 없는 활동',
      'week_events': '이번 주 활동',
      'more_apps': '다른 앱 보기',
      'more_apps_desc': 'DangunDad의 다른 앱도 볼 수 있어요',
      'privacy_policy': '개인정보 처리방침',
      'privacy_policy_desc': '로컬 데이터와 권한이 어떻게 처리되는지 볼 수 있어요',
      'link_open_error': '지금은 링크를 열지 못했어요. 잠시 후 다시 시도해 주세요.',
      'save': '저장',
      'saved': '저장됨',
      'save_canvas': '캔버스 저장',
      'save_success': '그림을 저장했어요',
      'save_error': '그림을 저장하지 못했어요. 다시 시도해 주세요.',
      'gallery': '갤러리',
      'gallery_empty': '저장한 그림이 아직 없어요',
      'gallery_subtitle': '저장한 그림을 불러오거나 공유할 수 있어요',
      'saved_drawings': '저장된 그림',
      'load_drawing': '불러오기',
      'load_drawing_message': '이 이미지를 참고하면서 새 그림을 시작해요.',
      'load_drawing_confirm': '지금 그림을 지우고 저장한 그림을 불러올까요?',
      'delete_drawing': '그림 삭제',
      'delete_drawing_complete': '그림을 지웠어요.',
      'delete_drawing_confirm': '이 그림을 지울까요?',
      'delete_error': '그림을 지우지 못했어요. 다시 시도해 주세요.',
      'share_error': '그림을 공유하지 못했어요. 다시 시도해 주세요.',
      'watercolor_brush': '수채화 브러시',
      'airbrush_brush': '에어브러시',
      'watercolor_mode': '수채화 모드',
      'airbrush_mode': '에어브러시 모드',
      'brush_unlock_message': '짧은 광고를 보면 이 브러시를 계속 쓸 수 있어요!',
      'brush_unlocked': '브러시 잠금 해제!',
      'watch_ad': '광고 보기',
      'nav_home': '홈',
      'nav_gallery': '갤러리',
      'nav_history': '기록',
      'nav_stats': '통계',
    },
  };
}
