import 'package:flutter/material.dart';
import 'package:get/get.dart';

class Languages extends Translations {
  static const List<Locale> supportedLocales = [
    Locale('en'), // 미국 영어
    Locale('ko'), // 대한민국 한국어
    Locale('ja'), // 일본어
    Locale('de'), // 독일어
    Locale('ru'), // 러시아어
    Locale('fr'), // 프랑스어
    Locale('es'), // 스페인어
    Locale('pt'), // 포르투갈어
    Locale('id'), // 인도네시아어
    Locale('zh'), // 중국어
    Locale('ar'), // 아랍어
  ];

  @override
  Map<String, Map<String, String>> get keys => {
    'en': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Draw freely and share',
      'ask_before_clear': 'Confirm before clearing',
      'ask_before_clear_desc':
          'Ask for confirmation before erasing all strokes',
      'back': 'Back',
      'brush_guide': 'Brush Guide',
      'brush_guide_desc':
          'Change brushes below and drag the slider to adjust size',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'clear_all': 'Clear All',
      'clear_canvas': 'Clear Canvas',
      'clear_canvas_confirm': 'Clear all content on the canvas?',
      'clear_data': 'Clear Local Data',
      'clear_data_complete': 'Local data is cleared.',
      'clear_data_confirm': 'Clear local settings and activity history?',
      'clear_data_desc': 'Reset app settings and activity history',
      'confirm': 'Confirm',
      'data_and_support': 'Data & Support',
      'drawing_settings': 'Drawing Settings',
      'eraser_mode': 'Eraser Mode',
      'error': 'Error',
      'exit': 'Exit',
      'exit_app_message': 'Your saved drawings stay on this device.',
      'exit_confirmation': 'Exit the app?',
      'feature_colors': 'Multiple Colors',
      'feature_eraser': 'Eraser',
      'feature_marker': 'Marker',
      'feature_pen': 'Pen',
      'feature_share': 'Share',
      'feature_undo': 'Undo',
      'feedback': 'Send Feedback',
      'feedback_desc': 'Send us your thoughts to improve the app',
      'feedback_tip': 'This feature is on the way. Thanks for waiting.',
      'feedback_email_subject': 'Doodle Pad Feedback',
      'haptic_feedback': 'Haptic Feedback',
      'haptic_feedback_desc': 'Vibrate when using drawing tools',
      'history': 'History',
      'history_subtitle': '@screen / @route',
      'language': 'Language',
      'no_history': 'No history yet.',
      'open_history': 'History',
      'open_history_desc': 'View previous drawings and activity',
      'open_stats': 'Stats',
      'open_stats_desc': 'View app usage statistics and activity',
      'premium_benefit_remove_ads': 'Remove Ads',
      'premium_benefit_statistics': 'Detailed Statistics',
      'premium_benefit_unlimited': 'Unlimited Drawing',
      'premium_benefits': 'Premium Benefits',
      'premium_owned': 'You Own Premium',
      'premium_support_large_desc': 'Give Doodle Pad strong support.',
      'premium_support_large_title': 'Large Support',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'A balanced way to remove ads and help.',
      'premium_support_medium_title': 'Medium Support',
      'premium_support_small_desc': 'A small thanks to keep the canvas clean.',
      'premium_support_small_title': 'Small Support',
      'premium_support_title': 'Support Doodle Pad',
      'premium_plan_monthly': 'Monthly Plan',
      'premium_plan_monthly_desc': 'Enjoy all premium features for 1 month',
      'premium_plan_title': 'Support Options',
      'premium_plan_weekly': 'Weekly Plan',
      'premium_plan_weekly_desc': 'Enjoy all premium features for 1 week',
      'premium_plan_yearly': 'Yearly Plan',
      'premium_plan_yearly_desc': 'Enjoy all premium features for 1 year',
      'premium_purchase': 'Support now',
      'premium_purchase_note': 'One-time support. Ads stay removed.',
      'premium_ready': 'Premium is ready.',
      'premium_restore': 'Restore purchases',
      'premium_subtitle': 'Remove ads and support future updates.',
      'premium_title': 'Premium',
      'purchase_error': "We couldn't complete your purchase.",
      'purchase_failed': "We couldn't complete your purchase.",
      'purchase_success': 'Purchase complete.',
      'purchase_unavailable': "Purchases aren't available right now.",
      'quick_actions': 'Quick Actions',
      'redo': 'Redo',
      'refresh': 'Refresh',
      'rate_app': 'Rate this App',
      'rate_app_desc': 'Leave a review on the store',
      'restore_error': "We couldn't restore your purchase yet.",
      'settings': 'Settings',
      'share': 'Share',
      'show_brush_guide': 'Show Brush Guide',
      'show_brush_guide_desc': 'Show the brush hint below the drawing toolbar',
      'start_drawing': 'Start Drawing',
      'stats': 'Statistics',
      'today_events': 'Today',
      'top_events': 'Top Activities',
      'total_events': 'Total Activities',
      'undo': 'Undo',
      'unique_routes': 'Screens Visited',
      'unique_screens': 'Unique Screens',
      'unknown_event': 'Unknown activity',
      'week_events': 'This Week',
      'more_apps': 'See More Apps',
      'more_apps_desc': 'Explore more apps from DangunDad',
      'privacy_policy': 'Privacy Policy',
      'privacy_policy_desc': 'See how local data and permissions are handled.',
      'link_open_error': "We couldn't open this link right now.",
      'save': 'Save',
      'saved': 'Saved',
      'save_canvas': 'Save Drawing',
      'save_success': 'Drawing saved.',
      'save_error': "We couldn't save your drawing.",
      'gallery': 'Gallery',
      'gallery_empty': 'No saved drawings yet',
      'gallery_subtitle': 'Load or share your saved drawings',
      'saved_drawings': 'Saved Drawings',
      'load_drawing': 'Load',
      'load_drawing_message':
          'Start a new drawing with this image for reference.',
      'load_drawing_confirm': 'Clear the current drawing and load this one?',
      'delete_drawing': 'Delete Drawing',
      'delete_drawing_complete': 'Drawing deleted.',
      'delete_drawing_confirm': 'Delete this drawing?',
      'delete_error': "We couldn't delete your drawing.",
      'share_error': "We couldn't share your drawing.",
      'watercolor_brush': 'Watercolor Brush',
      'airbrush_brush': 'Airbrush',
      'watercolor_mode': 'Watercolor Mode',
      'airbrush_mode': 'Airbrush Mode',
      'brush_unlock_message':
          'Watch a short ad to permanently unlock this brush!',
      'brush_unlocked': 'Brush Unlocked!',
      'watch_ad': 'Watch Ad',
      'nav_home': 'Home',
      'nav_gallery': 'Gallery',
      'nav_history': 'History',
      'nav_stats': 'Stats',
    },
    'ko': {
      'app_name': '두들 패드',
      'app_subtitle': '가볍게 그리고 바로 공유해요',
      'ask_before_clear': '지우기 전 확인',
      'ask_before_clear_desc': '모든 선을 지우기 전에 한 번 더 확인해요',
      'back': '뒤로',
      'brush_guide': '브러시 가이드',
      'brush_guide_desc': '아래에서 브러시를 바꾸고 슬라이더로 굵기를 조절해요',
      'cancel': '취소',
      'clear': '지우기',
      'clear_all': '모두 지우기',
      'clear_canvas': '캔버스 지우기',
      'clear_canvas_confirm': '캔버스를 모두 지울까요?',
      'clear_data': '로컬 데이터 지우기',
      'clear_data_complete': '로컬 데이터를 지웠어요.',
      'clear_data_confirm': '로컬 설정과 사용 기록을 지울까요?',
      'clear_data_desc': '앱 설정과 사용 기록을 지워요',
      'confirm': '확인',
      'data_and_support': '데이터 및 고객 지원',
      'drawing_settings': '그리기 설정',
      'eraser_mode': '지우개 모드',
      'error': '오류',
      'exit': '종료',
      'exit_app_message': '저장한 그림은 이 기기에 남아 있어요.',
      'exit_confirmation': '앱을 종료할까요?',
      'feature_colors': '다양한 색상',
      'feature_eraser': '지우개',
      'feature_marker': '마커',
      'feature_pen': '펜',
      'feature_share': '공유하기',
      'feature_undo': '실행 취소',
      'feedback': '피드백 보내기',
      'feedback_desc': '앱 개선을 위한 의견을 보내주세요',
      'feedback_tip': '이 기능을 준비하고 있어요. 조금만 기다려 주세요.',
      'feedback_email_subject': 'Doodle Pad 피드백',
      'haptic_feedback': '진동 피드백',
      'haptic_feedback_desc': '도구 사용 시 진동으로 반응을 줍니다',
      'history': '기록',
      'history_subtitle': '@screen / @route',
      'language': '언어',
      'no_history': '아직 기록이 없어요',
      'open_history': '기록',
      'open_history_desc': '이전 그림과 활동 내역을 볼 수 있어요',
      'open_stats': '통계',
      'open_stats_desc': '앱 사용 통계와 활동 내역을 볼 수 있어요',
      'premium_benefit_remove_ads': '광고 제거',
      'premium_benefit_statistics': '상세 통계 확인',
      'premium_benefit_unlimited': '무제한 그리기',
      'premium_benefits': '프리미엄 혜택',
      'premium_owned': '프리미엄을 쓰고 있어요',
      'premium_support_large_desc': '두들 패드를 크게 후원해요.',
      'premium_support_large_title': '큰 후원',
      'premium_support_medium_badge': '인기',
      'premium_support_medium_desc': '광고 제거와 후원을 함께해요.',
      'premium_support_medium_title': '중간 후원',
      'premium_support_small_desc': '깨끗한 캔버스를 가볍게 응원해요.',
      'premium_support_small_title': '작은 후원',
      'premium_support_title': '두들 패드 후원',
      'premium_plan_monthly': '월간 요금제',
      'premium_plan_monthly_desc': '1개월 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_plan_title': '후원 선택',
      'premium_plan_weekly': '주간 요금제',
      'premium_plan_weekly_desc': '1주일 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_plan_yearly': '연간 요금제',
      'premium_plan_yearly_desc': '1년 동안 모든 프리미엄 혜택을 쓸 수 있어요',
      'premium_purchase': '후원하기',
      'premium_purchase_note': '1회 후원으로 광고가 제거됩니다.',
      'premium_ready': '프리미엄을 바로 쓸 수 있어요.',
      'premium_restore': '구매 내역 복원',
      'premium_subtitle': '광고를 없애고 다음 업데이트를 응원해요.',
      'premium_title': '프리미엄',
      'purchase_error': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_failed': '구매를 완료하지 못했어요. 잠시 후 다시 시도해 주세요.',
      'purchase_success': '구매를 완료했어요.',
      'purchase_unavailable': '지금은 구매를 이용하기 어려워요. 잠시 후 다시 시도해 주세요.',
      'quick_actions': '빠른 실행',
      'redo': '다시 실행',
      'refresh': '새로고침',
      'rate_app': '앱 평가하기',
      'rate_app_desc': '스토어에 리뷰를 남겨주세요',
      'restore_error': '구매 내역을 아직 불러오지 못했어요. 잠시 후 다시 시도해 주세요.',
      'settings': '설정',
      'share': '공유하기',
      'show_brush_guide': '브러시 가이드 표시',
      'show_brush_guide_desc': '그리기 도구 막대 아래에 브러시 힌트를 보여줘요',
      'start_drawing': '그리기 시작',
      'stats': '통계',
      'today_events': '오늘의 활동',
      'top_events': '주요 활동',
      'total_events': '전체 활동',
      'undo': '실행 취소',
      'unique_routes': '방문한 화면 수',
      'unique_screens': '고유 화면 수',
      'unknown_event': '알 수 없는 활동',
      'week_events': '이번 주 활동',
      'more_apps': '다른 앱 보기',
      'more_apps_desc': 'DangunDad의 다른 앱도 볼 수 있어요',
      'privacy_policy': '개인정보 처리방침',
      'privacy_policy_desc': '로컬 데이터와 권한이 어떻게 처리되는지 볼 수 있어요',
      'link_open_error': '지금은 링크를 열지 못했어요. 잠시 후 다시 시도해 주세요.',
      'save': '저장',
      'saved': '저장됨',
      'save_canvas': '캔버스 저장',
      'save_success': '그림을 저장했어요',
      'save_error': '그림을 저장하지 못했어요. 다시 시도해 주세요.',
      'gallery': '갤러리',
      'gallery_empty': '저장한 그림이 아직 없어요',
      'gallery_subtitle': '저장한 그림을 불러오거나 공유할 수 있어요',
      'saved_drawings': '저장된 그림',
      'load_drawing': '불러오기',
      'load_drawing_message': '이 이미지를 참고하면서 새 그림을 시작해요.',
      'load_drawing_confirm': '지금 그림을 지우고 저장한 그림을 불러올까요?',
      'delete_drawing': '그림 삭제',
      'delete_drawing_complete': '그림을 지웠어요.',
      'delete_drawing_confirm': '이 그림을 지울까요?',
      'delete_error': '그림을 지우지 못했어요. 다시 시도해 주세요.',
      'share_error': '그림을 공유하지 못했어요. 다시 시도해 주세요.',
      'watercolor_brush': '수채화 브러시',
      'airbrush_brush': '에어브러시',
      'watercolor_mode': '수채화 모드',
      'airbrush_mode': '에어브러시 모드',
      'brush_unlock_message': '짧은 광고를 보면 이 브러시를 계속 쓸 수 있어요!',
      'brush_unlocked': '브러시 잠금 해제!',
      'watch_ad': '광고 보기',
      'nav_home': '홈',
      'nav_gallery': '갤러리',
      'nav_history': '기록',
      'nav_stats': '통계',
    },
    'ja': {
      'app_name': 'ドゥードルパッド',
      'app_subtitle': '自由に描いてすぐ共有',
      'ask_before_clear': '消去前に確認',
      'ask_before_clear_desc': 'すべての線を消す前に確認します',
      'back': '戻る',
      'brush_guide': 'ブラシガイド',
      'brush_guide_desc': '下でブラシを選び、スライダーで太さを調整',
      'cancel': 'キャンセル',
      'clear': '消去',
      'clear_all': 'すべて消去',
      'clear_canvas': 'キャンバスを消去',
      'clear_canvas_confirm': 'キャンバスをすべて消去しますか？',
      'clear_data': 'ローカルデータを消去',
      'clear_data_complete': 'ローカルデータを消去しました。',
      'clear_data_confirm': '設定と履歴を消去しますか？',
      'clear_data_desc': '設定と使用履歴をリセット',
      'confirm': '確認',
      'data_and_support': 'データとサポート',
      'drawing_settings': '描画設定',
      'eraser_mode': '消しゴムモード',
      'error': 'エラー',
      'exit': '終了',
      'exit_app_message': '保存した絵はこの端末に残ります。',
      'exit_confirmation': 'アプリを終了しますか？',
      'feature_colors': '多彩な色',
      'feature_eraser': '消しゴム',
      'feature_marker': 'マーカー',
      'feature_pen': 'ペン',
      'feature_share': '共有',
      'feature_undo': '元に戻す',
      'feedback': 'フィードバック',
      'feedback_desc': '改善のご意見をお送りください',
      'feedback_tip': 'この機能は準備中です。しばらくお待ちください。',
      'feedback_email_subject': 'Doodle Pad フィードバック',
      'haptic_feedback': '触覚フィードバック',
      'haptic_feedback_desc': 'ツール操作時に振動します',
      'history': '履歴',
      'history_subtitle': '@screen / @route',
      'language': '言語',
      'no_history': '履歴はまだありません。',
      'open_history': '履歴',
      'open_history_desc': '過去の絵と操作履歴を表示',
      'open_stats': '統計',
      'open_stats_desc': '使用状況と操作履歴を表示',
      'premium_benefit_remove_ads': '広告を削除',
      'premium_benefit_statistics': '詳細な統計',
      'premium_benefit_unlimited': '無制限に描画',
      'premium_benefits': 'プレミアム特典',
      'premium_owned': 'プレミアム利用中',
      'premium_support_large_desc': 'Doodle Padを大きく応援。',
      'premium_support_large_title': '大きく応援',
      'premium_support_medium_badge': '人気',
      'premium_support_medium_desc': '広告削除と応援にちょうどいい。',
      'premium_support_medium_title': 'ふつうに応援',
      'premium_support_small_desc': 'きれいなキャンバスを少し応援。',
      'premium_support_small_title': '少し応援',
      'premium_support_title': 'Doodle Padを応援',
      'premium_plan_monthly': '月間プラン',
      'premium_plan_monthly_desc': '1か月すべての特典を利用',
      'premium_plan_title': '応援を選択',
      'premium_plan_weekly': '週間プラン',
      'premium_plan_weekly_desc': '1週間すべての特典を利用',
      'premium_plan_yearly': '年間プラン',
      'premium_plan_yearly_desc': '1年間すべての特典を利用',
      'premium_purchase': '応援する',
      'premium_purchase_note': '一度の応援で広告が消えます。',
      'premium_ready': 'プレミアムを利用できます。',
      'premium_restore': '購入を復元',
      'premium_subtitle': '広告を消して今後の更新を応援。',
      'premium_title': 'プレミアム',
      'purchase_error': '購入を完了できませんでした。',
      'purchase_failed': '購入を完了できませんでした。',
      'purchase_success': '購入が完了しました。',
      'purchase_unavailable': '現在購入できません。',
      'quick_actions': 'クイック操作',
      'redo': 'やり直す',
      'refresh': '更新',
      'rate_app': 'アプリを評価',
      'rate_app_desc': 'ストアにレビューを投稿',
      'restore_error': '購入を復元できませんでした。',
      'settings': '設定',
      'share': '共有',
      'show_brush_guide': 'ブラシガイドを表示',
      'show_brush_guide_desc': '描画ツールバー下にヒントを表示',
      'start_drawing': '描き始める',
      'stats': '統計',
      'today_events': '今日',
      'top_events': '主なアクティビティ',
      'total_events': '全アクティビティ',
      'undo': '元に戻す',
      'unique_routes': '表示した画面',
      'unique_screens': '画面数',
      'unknown_event': '不明な操作',
      'week_events': '今週',
      'more_apps': '他のアプリ',
      'more_apps_desc': 'DangunDad の他のアプリを見る',
      'privacy_policy': 'プライバシーポリシー',
      'privacy_policy_desc': 'データと権限の扱いを確認',
      'link_open_error': 'リンクを開けませんでした。',
      'save': '保存',
      'saved': '保存済み',
      'save_canvas': '絵を保存',
      'save_success': '絵を保存しました。',
      'save_error': '絵を保存できませんでした。',
      'gallery': 'ギャラリー',
      'gallery_empty': '保存した絵はまだありません',
      'gallery_subtitle': '保存した絵を開く・共有',
      'saved_drawings': '保存した絵',
      'load_drawing': '開く',
      'load_drawing_message': 'この画像を参考に新しく描きます。',
      'load_drawing_confirm': '現在の絵を消して開きますか？',
      'delete_drawing': '絵を削除',
      'delete_drawing_complete': '絵を削除しました。',
      'delete_drawing_confirm': 'この絵を削除しますか？',
      'delete_error': '絵を削除できませんでした。',
      'share_error': '絵を共有できませんでした。',
      'watercolor_brush': '水彩ブラシ',
      'airbrush_brush': 'エアブラシ',
      'watercolor_mode': '水彩モード',
      'airbrush_mode': 'エアブラシモード',
      'brush_unlock_message': '短い広告を見るとこのブラシを解除できます。',
      'brush_unlocked': 'ブラシを解除しました',
      'watch_ad': '広告を見る',
      'nav_home': 'ホーム',
      'nav_gallery': 'ギャラリー',
      'nav_history': '履歴',
      'nav_stats': '統計',
    },
    'de': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Frei zeichnen und teilen',
      'ask_before_clear': 'Vor dem Löschen fragen',
      'ask_before_clear_desc': 'Vor dem Entfernen aller Striche bestätigen',
      'back': 'Zurück',
      'brush_guide': 'Pinselhilfe',
      'brush_guide_desc': 'Pinsel unten wählen und Größe per Regler ändern',
      'cancel': 'Abbrechen',
      'clear': 'Löschen',
      'clear_all': 'Alles löschen',
      'clear_canvas': 'Leinwand löschen',
      'clear_canvas_confirm': 'Alles auf der Leinwand löschen?',
      'clear_data': 'Lokale Daten löschen',
      'clear_data_complete': 'Lokale Daten wurden gelöscht.',
      'clear_data_confirm': 'Einstellungen und Verlauf löschen?',
      'clear_data_desc': 'Einstellungen und Verlauf zurücksetzen',
      'confirm': 'Bestätigen',
      'data_and_support': 'Daten & Support',
      'drawing_settings': 'Zeicheneinstellungen',
      'eraser_mode': 'Radiermodus',
      'error': 'Fehler',
      'exit': 'Beenden',
      'exit_app_message': 'Gespeicherte Zeichnungen bleiben auf diesem Gerät.',
      'exit_confirmation': 'App beenden?',
      'feature_colors': 'Viele Farben',
      'feature_eraser': 'Radierer',
      'feature_marker': 'Marker',
      'feature_pen': 'Stift',
      'feature_share': 'Teilen',
      'feature_undo': 'Rückgängig',
      'feedback': 'Feedback senden',
      'feedback_desc': 'Teile deine Ideen zur Verbesserung',
      'feedback_tip': 'Diese Funktion ist in Arbeit. Danke für deine Geduld.',
      'feedback_email_subject': 'Doodle Pad Feedback',
      'haptic_feedback': 'Haptisches Feedback',
      'haptic_feedback_desc': 'Vibrieren bei Werkzeugaktionen',
      'history': 'Verlauf',
      'history_subtitle': '@screen / @route',
      'language': 'Sprache',
      'no_history': 'Noch kein Verlauf.',
      'open_history': 'Verlauf',
      'open_history_desc': 'Frühere Zeichnungen und Aktivitäten ansehen',
      'open_stats': 'Statistik',
      'open_stats_desc': 'Nutzung und Aktivitäten ansehen',
      'premium_benefit_remove_ads': 'Werbung entfernen',
      'premium_benefit_statistics': 'Detaillierte Statistik',
      'premium_benefit_unlimited': 'Unbegrenzt zeichnen',
      'premium_benefits': 'Premium-Vorteile',
      'premium_owned': 'Premium ist aktiv',
      'premium_support_large_desc': 'Unterstütze Doodle Pad besonders stark.',
      'premium_support_large_title': 'Große Unterstützung',
      'premium_support_medium_badge': 'Beliebt',
      'premium_support_medium_desc':
          'Ein guter Weg, Werbung zu entfernen und zu helfen.',
      'premium_support_medium_title': 'Mittlere Unterstützung',
      'premium_support_small_desc':
          'Ein kleines Danke für eine saubere Leinwand.',
      'premium_support_small_title': 'Kleine Unterstützung',
      'premium_support_title': 'Doodle Pad unterstützen',
      'premium_plan_monthly': 'Monatsplan',
      'premium_plan_monthly_desc': 'Alle Premium-Funktionen für 1 Monat',
      'premium_plan_title': 'Unterstützung wählen',
      'premium_plan_weekly': 'Wochenplan',
      'premium_plan_weekly_desc': 'Alle Premium-Funktionen für 1 Woche',
      'premium_plan_yearly': 'Jahresplan',
      'premium_plan_yearly_desc': 'Alle Premium-Funktionen für 1 Jahr',
      'premium_purchase': 'Jetzt unterstützen',
      'premium_purchase_note': 'Einmalige Unterstützung. Werbung bleibt weg.',
      'premium_ready': 'Premium ist bereit.',
      'premium_restore': 'Käufe wiederherstellen',
      'premium_subtitle': 'Entferne Werbung und unterstütze Updates.',
      'premium_title': 'Premium',
      'purchase_error': 'Der Kauf konnte nicht abgeschlossen werden.',
      'purchase_failed': 'Der Kauf konnte nicht abgeschlossen werden.',
      'purchase_success': 'Kauf abgeschlossen.',
      'purchase_unavailable': 'Käufe sind gerade nicht verfügbar.',
      'quick_actions': 'Schnellaktionen',
      'redo': 'Wiederholen',
      'refresh': 'Aktualisieren',
      'rate_app': 'App bewerten',
      'rate_app_desc': 'Bewertung im Store hinterlassen',
      'restore_error': 'Kauf konnte nicht wiederhergestellt werden.',
      'settings': 'Einstellungen',
      'share': 'Teilen',
      'show_brush_guide': 'Pinselhilfe anzeigen',
      'show_brush_guide_desc': 'Hinweis unter der Werkzeugleiste anzeigen',
      'start_drawing': 'Zeichnen starten',
      'stats': 'Statistik',
      'today_events': 'Heute',
      'top_events': 'Top-Aktivitäten',
      'total_events': 'Alle Aktivitäten',
      'undo': 'Rückgängig',
      'unique_routes': 'Besuchte Seiten',
      'unique_screens': 'Einzelne Seiten',
      'unknown_event': 'Unbekannte Aktivität',
      'week_events': 'Diese Woche',
      'more_apps': 'Weitere Apps',
      'more_apps_desc': 'Weitere Apps von DangunDad ansehen',
      'privacy_policy': 'Datenschutz',
      'privacy_policy_desc': 'Umgang mit Daten und Berechtigungen ansehen',
      'link_open_error': 'Link konnte nicht geöffnet werden.',
      'save': 'Speichern',
      'saved': 'Gespeichert',
      'save_canvas': 'Zeichnung speichern',
      'save_success': 'Zeichnung gespeichert.',
      'save_error': 'Zeichnung konnte nicht gespeichert werden.',
      'gallery': 'Galerie',
      'gallery_empty': 'Noch keine gespeicherten Zeichnungen',
      'gallery_subtitle': 'Gespeicherte Zeichnungen öffnen oder teilen',
      'saved_drawings': 'Gespeicherte Zeichnungen',
      'load_drawing': 'Laden',
      'load_drawing_message': 'Mit diesem Bild als Vorlage neu zeichnen.',
      'load_drawing_confirm': 'Aktuelle Zeichnung löschen und diese laden?',
      'delete_drawing': 'Zeichnung löschen',
      'delete_drawing_complete': 'Zeichnung gelöscht.',
      'delete_drawing_confirm': 'Diese Zeichnung löschen?',
      'delete_error': 'Zeichnung konnte nicht gelöscht werden.',
      'share_error': 'Zeichnung konnte nicht geteilt werden.',
      'watercolor_brush': 'Aquarellpinsel',
      'airbrush_brush': 'Airbrush',
      'watercolor_mode': 'Aquarellmodus',
      'airbrush_mode': 'Airbrush-Modus',
      'brush_unlock_message':
          'Sieh eine kurze Anzeige, um diesen Pinsel freizuschalten.',
      'brush_unlocked': 'Pinsel freigeschaltet',
      'watch_ad': 'Anzeige ansehen',
      'nav_home': 'Start',
      'nav_gallery': 'Galerie',
      'nav_history': 'Verlauf',
      'nav_stats': 'Statistik',
    },
    'ru': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Рисуйте свободно и делитесь',
      'ask_before_clear': 'Подтверждать очистку',
      'ask_before_clear_desc': 'Спрашивать перед удалением всех штрихов',
      'back': 'Назад',
      'brush_guide': 'Подсказка кистей',
      'brush_guide_desc': 'Выберите кисть ниже и настройте размер',
      'cancel': 'Отмена',
      'clear': 'Очистить',
      'clear_all': 'Очистить всё',
      'clear_canvas': 'Очистить холст',
      'clear_canvas_confirm': 'Очистить весь холст?',
      'clear_data': 'Очистить данные',
      'clear_data_complete': 'Локальные данные очищены.',
      'clear_data_confirm': 'Очистить настройки и историю?',
      'clear_data_desc': 'Сбросить настройки и историю',
      'confirm': 'Подтвердить',
      'data_and_support': 'Данные и поддержка',
      'drawing_settings': 'Настройки рисования',
      'eraser_mode': 'Режим ластика',
      'error': 'Ошибка',
      'exit': 'Выйти',
      'exit_app_message': 'Сохранённые рисунки останутся на устройстве.',
      'exit_confirmation': 'Выйти из приложения?',
      'feature_colors': 'Много цветов',
      'feature_eraser': 'Ластик',
      'feature_marker': 'Маркер',
      'feature_pen': 'Перо',
      'feature_share': 'Поделиться',
      'feature_undo': 'Отмена',
      'feedback': 'Отправить отзыв',
      'feedback_desc': 'Поделитесь идеями по улучшению',
      'feedback_tip': 'Функция скоро появится. Спасибо за ожидание.',
      'feedback_email_subject': 'Отзыв о Doodle Pad',
      'haptic_feedback': 'Виброотклик',
      'haptic_feedback_desc': 'Вибрация при использовании инструментов',
      'history': 'История',
      'history_subtitle': '@screen / @route',
      'language': 'Язык',
      'no_history': 'Истории пока нет.',
      'open_history': 'История',
      'open_history_desc': 'Просмотр рисунков и действий',
      'open_stats': 'Статистика',
      'open_stats_desc': 'Просмотр использования и действий',
      'premium_benefit_remove_ads': 'Без рекламы',
      'premium_benefit_statistics': 'Подробная статистика',
      'premium_benefit_unlimited': 'Рисование без ограничений',
      'premium_benefits': 'Преимущества Premium',
      'premium_owned': 'Premium активен',
      'premium_support_large_desc': 'Сильно поддержать Doodle Pad.',
      'premium_support_large_title': 'Большая поддержка',
      'premium_support_medium_badge': 'Популярно',
      'premium_support_medium_desc': 'Убрать рекламу и поддержать проект.',
      'premium_support_medium_title': 'Средняя поддержка',
      'premium_support_small_desc': 'Небольшое спасибо за чистый холст.',
      'premium_support_small_title': 'Малая поддержка',
      'premium_support_title': 'Поддержать Doodle Pad',
      'premium_plan_monthly': 'Месячный план',
      'premium_plan_monthly_desc': 'Все функции Premium на 1 месяц',
      'premium_plan_title': 'Варианты поддержки',
      'premium_plan_weekly': 'Недельный план',
      'premium_plan_weekly_desc': 'Все функции Premium на 1 неделю',
      'premium_plan_yearly': 'Годовой план',
      'premium_plan_yearly_desc': 'Все функции Premium на 1 год',
      'premium_purchase': 'Поддержать',
      'premium_purchase_note': 'Разовая поддержка. Реклама будет удалена.',
      'premium_ready': 'Premium готов.',
      'premium_restore': 'Восстановить покупки',
      'premium_subtitle': 'Уберите рекламу и поддержите обновления.',
      'premium_title': 'Premium',
      'purchase_error': 'Не удалось завершить покупку.',
      'purchase_failed': 'Не удалось завершить покупку.',
      'purchase_success': 'Покупка завершена.',
      'purchase_unavailable': 'Покупки сейчас недоступны.',
      'quick_actions': 'Быстрые действия',
      'redo': 'Повторить',
      'refresh': 'Обновить',
      'rate_app': 'Оценить приложение',
      'rate_app_desc': 'Оставьте отзыв в магазине',
      'restore_error': 'Не удалось восстановить покупку.',
      'settings': 'Настройки',
      'share': 'Поделиться',
      'show_brush_guide': 'Показать подсказку кистей',
      'show_brush_guide_desc': 'Показывать подсказку под панелью рисования',
      'start_drawing': 'Начать рисовать',
      'stats': 'Статистика',
      'today_events': 'Сегодня',
      'top_events': 'Главные действия',
      'total_events': 'Все действия',
      'undo': 'Отменить',
      'unique_routes': 'Посещённые экраны',
      'unique_screens': 'Уникальные экраны',
      'unknown_event': 'Неизвестное действие',
      'week_events': 'На этой неделе',
      'more_apps': 'Другие приложения',
      'more_apps_desc': 'Посмотреть другие приложения DangunDad',
      'privacy_policy': 'Политика конфиденциальности',
      'privacy_policy_desc': 'Как используются данные и разрешения',
      'link_open_error': 'Не удалось открыть ссылку.',
      'save': 'Сохранить',
      'saved': 'Сохранено',
      'save_canvas': 'Сохранить рисунок',
      'save_success': 'Рисунок сохранён.',
      'save_error': 'Не удалось сохранить рисунок.',
      'gallery': 'Галерея',
      'gallery_empty': 'Сохранённых рисунков пока нет',
      'gallery_subtitle': 'Открывайте или делитесь рисунками',
      'saved_drawings': 'Сохранённые рисунки',
      'load_drawing': 'Открыть',
      'load_drawing_message': 'Начните новый рисунок с этим изображением.',
      'load_drawing_confirm': 'Очистить текущий рисунок и открыть этот?',
      'delete_drawing': 'Удалить рисунок',
      'delete_drawing_complete': 'Рисунок удалён.',
      'delete_drawing_confirm': 'Удалить этот рисунок?',
      'delete_error': 'Не удалось удалить рисунок.',
      'share_error': 'Не удалось поделиться рисунком.',
      'watercolor_brush': 'Акварельная кисть',
      'airbrush_brush': 'Аэрограф',
      'watercolor_mode': 'Акварель',
      'airbrush_mode': 'Аэрограф',
      'brush_unlock_message':
          'Посмотрите короткую рекламу, чтобы открыть кисть.',
      'brush_unlocked': 'Кисть открыта',
      'watch_ad': 'Смотреть рекламу',
      'nav_home': 'Главная',
      'nav_gallery': 'Галерея',
      'nav_history': 'История',
      'nav_stats': 'Статистика',
    },
    'fr': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Dessinez librement et partagez',
      'ask_before_clear': 'Confirmer avant d’effacer',
      'ask_before_clear_desc': 'Demander avant de supprimer tous les traits',
      'back': 'Retour',
      'brush_guide': 'Guide des pinceaux',
      'brush_guide_desc': 'Choisissez un pinceau et réglez la taille',
      'cancel': 'Annuler',
      'clear': 'Effacer',
      'clear_all': 'Tout effacer',
      'clear_canvas': 'Effacer la toile',
      'clear_canvas_confirm': 'Effacer tout le contenu ?',
      'clear_data': 'Effacer les données',
      'clear_data_complete': 'Données locales effacées.',
      'clear_data_confirm': 'Effacer les réglages et l’historique ?',
      'clear_data_desc': 'Réinitialiser les réglages et l’historique',
      'confirm': 'Confirmer',
      'data_and_support': 'Données et support',
      'drawing_settings': 'Réglages de dessin',
      'eraser_mode': 'Mode gomme',
      'error': 'Erreur',
      'exit': 'Quitter',
      'exit_app_message': 'Vos dessins enregistrés restent sur cet appareil.',
      'exit_confirmation': 'Quitter l’appli ?',
      'feature_colors': 'Nombreuses couleurs',
      'feature_eraser': 'Gomme',
      'feature_marker': 'Marqueur',
      'feature_pen': 'Stylo',
      'feature_share': 'Partager',
      'feature_undo': 'Annuler',
      'feedback': 'Envoyer un avis',
      'feedback_desc': 'Partagez vos idées d’amélioration',
      'feedback_tip': 'Cette fonction arrive bientôt. Merci de patienter.',
      'feedback_email_subject': 'Avis sur Doodle Pad',
      'haptic_feedback': 'Retour haptique',
      'haptic_feedback_desc': 'Vibrer lors de l’utilisation des outils',
      'history': 'Historique',
      'history_subtitle': '@screen / @route',
      'language': 'Langue',
      'no_history': 'Aucun historique pour le moment.',
      'open_history': 'Historique',
      'open_history_desc': 'Voir les dessins et activités passés',
      'open_stats': 'Stats',
      'open_stats_desc': 'Voir l’utilisation et les activités',
      'premium_benefit_remove_ads': 'Supprimer les pubs',
      'premium_benefit_statistics': 'Statistiques détaillées',
      'premium_benefit_unlimited': 'Dessin illimité',
      'premium_benefits': 'Avantages Premium',
      'premium_owned': 'Premium activé',
      'premium_support_large_desc': 'Soutien fort pour Doodle Pad.',
      'premium_support_large_title': 'Grand soutien',
      'premium_support_medium_badge': 'Populaire',
      'premium_support_medium_desc': 'Supprime les pubs et aide le projet.',
      'premium_support_medium_title': 'Soutien moyen',
      'premium_support_small_desc': 'Un petit merci pour une toile propre.',
      'premium_support_small_title': 'Petit soutien',
      'premium_support_title': 'Soutenir Doodle Pad',
      'premium_plan_monthly': 'Forfait mensuel',
      'premium_plan_monthly_desc':
          'Toutes les fonctions Premium pendant 1 mois',
      'premium_plan_title': 'Choisir un soutien',
      'premium_plan_weekly': 'Forfait hebdo',
      'premium_plan_weekly_desc':
          'Toutes les fonctions Premium pendant 1 semaine',
      'premium_plan_yearly': 'Forfait annuel',
      'premium_plan_yearly_desc': 'Toutes les fonctions Premium pendant 1 an',
      'premium_purchase': 'Soutenir',
      'premium_purchase_note': 'Soutien unique. Les pubs restent supprimées.',
      'premium_ready': 'Premium est prêt.',
      'premium_restore': 'Restaurer les achats',
      'premium_subtitle': 'Supprimez les pubs et soutenez les mises à jour.',
      'premium_title': 'Premium',
      'purchase_error': 'Achat impossible.',
      'purchase_failed': 'Achat impossible.',
      'purchase_success': 'Achat terminé.',
      'purchase_unavailable': 'Achats indisponibles pour le moment.',
      'quick_actions': 'Actions rapides',
      'redo': 'Rétablir',
      'refresh': 'Actualiser',
      'rate_app': 'Noter l’application',
      'rate_app_desc': 'Laisser un avis sur le store',
      'restore_error': 'Restauration impossible.',
      'settings': 'Réglages',
      'share': 'Partager',
      'show_brush_guide': 'Afficher le guide',
      'show_brush_guide_desc': 'Afficher l’aide sous la barre de dessin',
      'start_drawing': 'Commencer à dessiner',
      'stats': 'Statistiques',
      'today_events': 'Aujourd’hui',
      'top_events': 'Activités principales',
      'total_events': 'Toutes les activités',
      'undo': 'Annuler',
      'unique_routes': 'Écrans visités',
      'unique_screens': 'Écrans uniques',
      'unknown_event': 'Activité inconnue',
      'week_events': 'Cette semaine',
      'more_apps': 'Autres apps',
      'more_apps_desc': 'Voir d’autres apps de DangunDad',
      'privacy_policy': 'Confidentialité',
      'privacy_policy_desc': 'Voir l’usage des données et permissions',
      'link_open_error': 'Impossible d’ouvrir ce lien.',
      'save': 'Enregistrer',
      'saved': 'Enregistré',
      'save_canvas': 'Enregistrer le dessin',
      'save_success': 'Dessin enregistré.',
      'save_error': 'Impossible d’enregistrer le dessin.',
      'gallery': 'Galerie',
      'gallery_empty': 'Aucun dessin enregistré',
      'gallery_subtitle': 'Ouvrir ou partager vos dessins',
      'saved_drawings': 'Dessins enregistrés',
      'load_drawing': 'Ouvrir',
      'load_drawing_message': 'Nouveau dessin avec cette image en référence.',
      'load_drawing_confirm': 'Effacer le dessin actuel et ouvrir celui-ci ?',
      'delete_drawing': 'Supprimer le dessin',
      'delete_drawing_complete': 'Dessin supprimé.',
      'delete_drawing_confirm': 'Supprimer ce dessin ?',
      'delete_error': 'Impossible de supprimer le dessin.',
      'share_error': 'Impossible de partager le dessin.',
      'watercolor_brush': 'Pinceau aquarelle',
      'airbrush_brush': 'Aérographe',
      'watercolor_mode': 'Mode aquarelle',
      'airbrush_mode': 'Mode aérographe',
      'brush_unlock_message':
          'Regardez une courte pub pour débloquer ce pinceau.',
      'brush_unlocked': 'Pinceau débloqué',
      'watch_ad': 'Voir la pub',
      'nav_home': 'Accueil',
      'nav_gallery': 'Galerie',
      'nav_history': 'Historique',
      'nav_stats': 'Stats',
    },
    'es': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Dibuja libremente y comparte',
      'ask_before_clear': 'Confirmar antes de borrar',
      'ask_before_clear_desc': 'Pedir confirmación antes de borrar todo',
      'back': 'Atrás',
      'brush_guide': 'Guía de pinceles',
      'brush_guide_desc': 'Elige un pincel abajo y ajusta el tamaño',
      'cancel': 'Cancelar',
      'clear': 'Borrar',
      'clear_all': 'Borrar todo',
      'clear_canvas': 'Borrar lienzo',
      'clear_canvas_confirm': '¿Borrar todo el lienzo?',
      'clear_data': 'Borrar datos locales',
      'clear_data_complete': 'Datos locales borrados.',
      'clear_data_confirm': '¿Borrar ajustes e historial?',
      'clear_data_desc': 'Restablecer ajustes e historial',
      'confirm': 'Confirmar',
      'data_and_support': 'Datos y soporte',
      'drawing_settings': 'Ajustes de dibujo',
      'eraser_mode': 'Modo borrador',
      'error': 'Error',
      'exit': 'Salir',
      'exit_app_message': 'Tus dibujos guardados quedan en este dispositivo.',
      'exit_confirmation': '¿Salir de la app?',
      'feature_colors': 'Muchos colores',
      'feature_eraser': 'Borrador',
      'feature_marker': 'Marcador',
      'feature_pen': 'Lápiz',
      'feature_share': 'Compartir',
      'feature_undo': 'Deshacer',
      'feedback': 'Enviar comentarios',
      'feedback_desc': 'Comparte ideas para mejorar la app',
      'feedback_tip': 'Esta función está en camino. Gracias por esperar.',
      'feedback_email_subject': 'Comentarios sobre Doodle Pad',
      'haptic_feedback': 'Respuesta háptica',
      'haptic_feedback_desc': 'Vibrar al usar herramientas',
      'history': 'Historial',
      'history_subtitle': '@screen / @route',
      'language': 'Idioma',
      'no_history': 'Aún no hay historial.',
      'open_history': 'Historial',
      'open_history_desc': 'Ver dibujos y actividad anteriores',
      'open_stats': 'Estadísticas',
      'open_stats_desc': 'Ver uso y actividad de la app',
      'premium_benefit_remove_ads': 'Quitar anuncios',
      'premium_benefit_statistics': 'Estadísticas detalladas',
      'premium_benefit_unlimited': 'Dibujo ilimitado',
      'premium_benefits': 'Ventajas Premium',
      'premium_owned': 'Tienes Premium',
      'premium_support_large_desc': 'Da un apoyo grande a Doodle Pad.',
      'premium_support_large_title': 'Apoyo grande',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'Quita anuncios y ayuda al proyecto.',
      'premium_support_medium_title': 'Apoyo medio',
      'premium_support_small_desc': 'Un pequeño gracias por un lienzo limpio.',
      'premium_support_small_title': 'Apoyo pequeño',
      'premium_support_title': 'Apoyar Doodle Pad',
      'premium_plan_monthly': 'Plan mensual',
      'premium_plan_monthly_desc': 'Todas las funciones Premium por 1 mes',
      'premium_plan_title': 'Elige apoyo',
      'premium_plan_weekly': 'Plan semanal',
      'premium_plan_weekly_desc': 'Todas las funciones Premium por 1 semana',
      'premium_plan_yearly': 'Plan anual',
      'premium_plan_yearly_desc': 'Todas las funciones Premium por 1 año',
      'premium_purchase': 'Apoyar ahora',
      'premium_purchase_note': 'Apoyo único. Los anuncios quedan fuera.',
      'premium_ready': 'Premium está listo.',
      'premium_restore': 'Restaurar compras',
      'premium_subtitle': 'Quita anuncios y apoya futuras mejoras.',
      'premium_title': 'Premium',
      'purchase_error': 'No se pudo completar la compra.',
      'purchase_failed': 'No se pudo completar la compra.',
      'purchase_success': 'Compra completada.',
      'purchase_unavailable': 'Las compras no están disponibles ahora.',
      'quick_actions': 'Acciones rápidas',
      'redo': 'Rehacer',
      'refresh': 'Actualizar',
      'rate_app': 'Calificar la app',
      'rate_app_desc': 'Deja una reseña en la tienda',
      'restore_error': 'No se pudo restaurar la compra.',
      'settings': 'Ajustes',
      'share': 'Compartir',
      'show_brush_guide': 'Mostrar guía de pinceles',
      'show_brush_guide_desc': 'Mostrar la ayuda bajo la barra de dibujo',
      'start_drawing': 'Empezar a dibujar',
      'stats': 'Estadísticas',
      'today_events': 'Hoy',
      'top_events': 'Actividad principal',
      'total_events': 'Actividad total',
      'undo': 'Deshacer',
      'unique_routes': 'Pantallas visitadas',
      'unique_screens': 'Pantallas únicas',
      'unknown_event': 'Actividad desconocida',
      'week_events': 'Esta semana',
      'more_apps': 'Más apps',
      'more_apps_desc': 'Explora más apps de DangunDad',
      'privacy_policy': 'Privacidad',
      'privacy_policy_desc': 'Ver cómo se usan datos y permisos',
      'link_open_error': 'No se pudo abrir el enlace.',
      'save': 'Guardar',
      'saved': 'Guardado',
      'save_canvas': 'Guardar dibujo',
      'save_success': 'Dibujo guardado.',
      'save_error': 'No se pudo guardar el dibujo.',
      'gallery': 'Galería',
      'gallery_empty': 'Aún no hay dibujos guardados',
      'gallery_subtitle': 'Abre o comparte tus dibujos guardados',
      'saved_drawings': 'Dibujos guardados',
      'load_drawing': 'Abrir',
      'load_drawing_message': 'Empieza un dibujo nuevo con esta imagen.',
      'load_drawing_confirm': '¿Borrar el dibujo actual y abrir este?',
      'delete_drawing': 'Borrar dibujo',
      'delete_drawing_complete': 'Dibujo borrado.',
      'delete_drawing_confirm': '¿Borrar este dibujo?',
      'delete_error': 'No se pudo borrar el dibujo.',
      'share_error': 'No se pudo compartir el dibujo.',
      'watercolor_brush': 'Pincel de acuarela',
      'airbrush_brush': 'Aerógrafo',
      'watercolor_mode': 'Modo acuarela',
      'airbrush_mode': 'Modo aerógrafo',
      'brush_unlock_message':
          'Mira un anuncio corto para desbloquear este pincel.',
      'brush_unlocked': 'Pincel desbloqueado',
      'watch_ad': 'Ver anuncio',
      'nav_home': 'Inicio',
      'nav_gallery': 'Galería',
      'nav_history': 'Historial',
      'nav_stats': 'Estadísticas',
    },
    'pt': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Desenhe livremente e compartilhe',
      'ask_before_clear': 'Confirmar antes de limpar',
      'ask_before_clear_desc': 'Pedir confirmação antes de apagar tudo',
      'back': 'Voltar',
      'brush_guide': 'Guia de pincéis',
      'brush_guide_desc': 'Escolha um pincel abaixo e ajuste o tamanho',
      'cancel': 'Cancelar',
      'clear': 'Limpar',
      'clear_all': 'Limpar tudo',
      'clear_canvas': 'Limpar tela',
      'clear_canvas_confirm': 'Limpar todo o conteúdo da tela?',
      'clear_data': 'Limpar dados locais',
      'clear_data_complete': 'Dados locais limpos.',
      'clear_data_confirm': 'Limpar configurações e histórico?',
      'clear_data_desc': 'Redefinir configurações e histórico',
      'confirm': 'Confirmar',
      'data_and_support': 'Dados e suporte',
      'drawing_settings': 'Configurações de desenho',
      'eraser_mode': 'Modo borracha',
      'error': 'Erro',
      'exit': 'Sair',
      'exit_app_message': 'Seus desenhos salvos ficam neste aparelho.',
      'exit_confirmation': 'Sair do app?',
      'feature_colors': 'Várias cores',
      'feature_eraser': 'Borracha',
      'feature_marker': 'Marcador',
      'feature_pen': 'Caneta',
      'feature_share': 'Compartilhar',
      'feature_undo': 'Desfazer',
      'feedback': 'Enviar feedback',
      'feedback_desc': 'Compartilhe ideias para melhorar o app',
      'feedback_tip': 'Este recurso está a caminho. Obrigado por esperar.',
      'feedback_email_subject': 'Feedback do Doodle Pad',
      'haptic_feedback': 'Feedback tátil',
      'haptic_feedback_desc': 'Vibrar ao usar ferramentas',
      'history': 'Histórico',
      'history_subtitle': '@screen / @route',
      'language': 'Idioma',
      'no_history': 'Ainda não há histórico.',
      'open_history': 'Histórico',
      'open_history_desc': 'Ver desenhos e atividades anteriores',
      'open_stats': 'Estatísticas',
      'open_stats_desc': 'Ver uso e atividades do app',
      'premium_benefit_remove_ads': 'Remover anúncios',
      'premium_benefit_statistics': 'Estatísticas detalhadas',
      'premium_benefit_unlimited': 'Desenho ilimitado',
      'premium_benefits': 'Benefícios Premium',
      'premium_owned': 'Premium ativo',
      'premium_support_large_desc': 'Dê um apoio forte ao Doodle Pad.',
      'premium_support_large_title': 'Apoio grande',
      'premium_support_medium_badge': 'Popular',
      'premium_support_medium_desc': 'Remove anúncios e ajuda o projeto.',
      'premium_support_medium_title': 'Apoio médio',
      'premium_support_small_desc': 'Um pequeno obrigado por uma tela limpa.',
      'premium_support_small_title': 'Apoio pequeno',
      'premium_support_title': 'Apoiar o Doodle Pad',
      'premium_plan_monthly': 'Plano mensal',
      'premium_plan_monthly_desc': 'Todos os recursos Premium por 1 mês',
      'premium_plan_title': 'Escolha o apoio',
      'premium_plan_weekly': 'Plano semanal',
      'premium_plan_weekly_desc': 'Todos os recursos Premium por 1 semana',
      'premium_plan_yearly': 'Plano anual',
      'premium_plan_yearly_desc': 'Todos os recursos Premium por 1 ano',
      'premium_purchase': 'Apoiar agora',
      'premium_purchase_note': 'Apoio único. Os anúncios ficam removidos.',
      'premium_ready': 'Premium pronto.',
      'premium_restore': 'Restaurar compras',
      'premium_subtitle': 'Remova anúncios e apoie futuras atualizações.',
      'premium_title': 'Premium',
      'purchase_error': 'Não foi possível concluir a compra.',
      'purchase_failed': 'Não foi possível concluir a compra.',
      'purchase_success': 'Compra concluída.',
      'purchase_unavailable': 'Compras indisponíveis no momento.',
      'quick_actions': 'Ações rápidas',
      'redo': 'Refazer',
      'refresh': 'Atualizar',
      'rate_app': 'Avaliar app',
      'rate_app_desc': 'Deixe uma avaliação na loja',
      'restore_error': 'Não foi possível restaurar a compra.',
      'settings': 'Configurações',
      'share': 'Compartilhar',
      'show_brush_guide': 'Mostrar guia de pincéis',
      'show_brush_guide_desc': 'Mostrar dica abaixo da barra de desenho',
      'start_drawing': 'Começar a desenhar',
      'stats': 'Estatísticas',
      'today_events': 'Hoje',
      'top_events': 'Principais atividades',
      'total_events': 'Todas as atividades',
      'undo': 'Desfazer',
      'unique_routes': 'Telas visitadas',
      'unique_screens': 'Telas únicas',
      'unknown_event': 'Atividade desconhecida',
      'week_events': 'Esta semana',
      'more_apps': 'Mais apps',
      'more_apps_desc': 'Veja mais apps da DangunDad',
      'privacy_policy': 'Privacidade',
      'privacy_policy_desc': 'Veja como dados e permissões são usados',
      'link_open_error': 'Não foi possível abrir o link.',
      'save': 'Salvar',
      'saved': 'Salvo',
      'save_canvas': 'Salvar desenho',
      'save_success': 'Desenho salvo.',
      'save_error': 'Não foi possível salvar o desenho.',
      'gallery': 'Galeria',
      'gallery_empty': 'Ainda não há desenhos salvos',
      'gallery_subtitle': 'Abra ou compartilhe seus desenhos',
      'saved_drawings': 'Desenhos salvos',
      'load_drawing': 'Abrir',
      'load_drawing_message': 'Comece um novo desenho com esta imagem.',
      'load_drawing_confirm': 'Limpar o desenho atual e abrir este?',
      'delete_drawing': 'Excluir desenho',
      'delete_drawing_complete': 'Desenho excluído.',
      'delete_drawing_confirm': 'Excluir este desenho?',
      'delete_error': 'Não foi possível excluir o desenho.',
      'share_error': 'Não foi possível compartilhar o desenho.',
      'watercolor_brush': 'Pincel aquarela',
      'airbrush_brush': 'Aerógrafo',
      'watercolor_mode': 'Modo aquarela',
      'airbrush_mode': 'Modo aerógrafo',
      'brush_unlock_message':
          'Veja um anúncio curto para desbloquear este pincel.',
      'brush_unlocked': 'Pincel desbloqueado',
      'watch_ad': 'Ver anúncio',
      'nav_home': 'Início',
      'nav_gallery': 'Galeria',
      'nav_history': 'Histórico',
      'nav_stats': 'Estatísticas',
    },
    'id': {
      'app_name': 'Doodle Pad',
      'app_subtitle': 'Gambar bebas dan bagikan',
      'ask_before_clear': 'Konfirmasi sebelum hapus',
      'ask_before_clear_desc': 'Minta konfirmasi sebelum menghapus semua garis',
      'back': 'Kembali',
      'brush_guide': 'Panduan kuas',
      'brush_guide_desc': 'Pilih kuas di bawah dan atur ukurannya',
      'cancel': 'Batal',
      'clear': 'Hapus',
      'clear_all': 'Hapus semua',
      'clear_canvas': 'Hapus kanvas',
      'clear_canvas_confirm': 'Hapus semua isi kanvas?',
      'clear_data': 'Hapus data lokal',
      'clear_data_complete': 'Data lokal dihapus.',
      'clear_data_confirm': 'Hapus pengaturan dan riwayat?',
      'clear_data_desc': 'Reset pengaturan dan riwayat',
      'confirm': 'Konfirmasi',
      'data_and_support': 'Data & dukungan',
      'drawing_settings': 'Pengaturan gambar',
      'eraser_mode': 'Mode penghapus',
      'error': 'Error',
      'exit': 'Keluar',
      'exit_app_message': 'Gambar tersimpan tetap di perangkat ini.',
      'exit_confirmation': 'Keluar dari aplikasi?',
      'feature_colors': 'Banyak warna',
      'feature_eraser': 'Penghapus',
      'feature_marker': 'Marker',
      'feature_pen': 'Pena',
      'feature_share': 'Bagikan',
      'feature_undo': 'Urungkan',
      'feedback': 'Kirim masukan',
      'feedback_desc': 'Bagikan ide untuk meningkatkan aplikasi',
      'feedback_tip':
          'Fitur ini sedang disiapkan. Terima kasih sudah menunggu.',
      'feedback_email_subject': 'Masukan Doodle Pad',
      'haptic_feedback': 'Umpan balik getar',
      'haptic_feedback_desc': 'Getar saat memakai alat gambar',
      'history': 'Riwayat',
      'history_subtitle': '@screen / @route',
      'language': 'Bahasa',
      'no_history': 'Belum ada riwayat.',
      'open_history': 'Riwayat',
      'open_history_desc': 'Lihat gambar dan aktivitas sebelumnya',
      'open_stats': 'Statistik',
      'open_stats_desc': 'Lihat penggunaan dan aktivitas aplikasi',
      'premium_benefit_remove_ads': 'Hapus iklan',
      'premium_benefit_statistics': 'Statistik detail',
      'premium_benefit_unlimited': 'Menggambar tanpa batas',
      'premium_benefits': 'Manfaat Premium',
      'premium_owned': 'Premium aktif',
      'premium_support_large_desc': 'Beri dukungan besar untuk Doodle Pad.',
      'premium_support_large_title': 'Dukungan besar',
      'premium_support_medium_badge': 'Populer',
      'premium_support_medium_desc': 'Hapus iklan dan bantu proyek ini.',
      'premium_support_medium_title': 'Dukungan sedang',
      'premium_support_small_desc': 'Terima kasih kecil untuk kanvas bersih.',
      'premium_support_small_title': 'Dukungan kecil',
      'premium_support_title': 'Dukung Doodle Pad',
      'premium_plan_monthly': 'Paket bulanan',
      'premium_plan_monthly_desc': 'Semua fitur Premium selama 1 bulan',
      'premium_plan_title': 'Pilih dukungan',
      'premium_plan_weekly': 'Paket mingguan',
      'premium_plan_weekly_desc': 'Semua fitur Premium selama 1 minggu',
      'premium_plan_yearly': 'Paket tahunan',
      'premium_plan_yearly_desc': 'Semua fitur Premium selama 1 tahun',
      'premium_purchase': 'Dukung sekarang',
      'premium_purchase_note': 'Dukungan sekali. Iklan tetap dihapus.',
      'premium_ready': 'Premium siap digunakan.',
      'premium_restore': 'Pulihkan pembelian',
      'premium_subtitle': 'Hapus iklan dan dukung pembaruan.',
      'premium_title': 'Premium',
      'purchase_error': 'Pembelian tidak dapat diselesaikan.',
      'purchase_failed': 'Pembelian tidak dapat diselesaikan.',
      'purchase_success': 'Pembelian selesai.',
      'purchase_unavailable': 'Pembelian belum tersedia saat ini.',
      'quick_actions': 'Aksi cepat',
      'redo': 'Ulangi',
      'refresh': 'Segarkan',
      'rate_app': 'Nilai aplikasi',
      'rate_app_desc': 'Tinggalkan ulasan di toko',
      'restore_error': 'Pembelian belum dapat dipulihkan.',
      'settings': 'Pengaturan',
      'share': 'Bagikan',
      'show_brush_guide': 'Tampilkan panduan kuas',
      'show_brush_guide_desc': 'Tampilkan petunjuk di bawah toolbar gambar',
      'start_drawing': 'Mulai menggambar',
      'stats': 'Statistik',
      'today_events': 'Hari ini',
      'top_events': 'Aktivitas utama',
      'total_events': 'Semua aktivitas',
      'undo': 'Urungkan',
      'unique_routes': 'Layar dikunjungi',
      'unique_screens': 'Layar unik',
      'unknown_event': 'Aktivitas tidak dikenal',
      'week_events': 'Minggu ini',
      'more_apps': 'Aplikasi lain',
      'more_apps_desc': 'Lihat aplikasi lain dari DangunDad',
      'privacy_policy': 'Privasi',
      'privacy_policy_desc': 'Lihat penggunaan data dan izin',
      'link_open_error': 'Tautan tidak dapat dibuka.',
      'save': 'Simpan',
      'saved': 'Tersimpan',
      'save_canvas': 'Simpan gambar',
      'save_success': 'Gambar disimpan.',
      'save_error': 'Gambar tidak dapat disimpan.',
      'gallery': 'Galeri',
      'gallery_empty': 'Belum ada gambar tersimpan',
      'gallery_subtitle': 'Buka atau bagikan gambar tersimpan',
      'saved_drawings': 'Gambar tersimpan',
      'load_drawing': 'Buka',
      'load_drawing_message': 'Mulai gambar baru dengan gambar ini.',
      'load_drawing_confirm': 'Hapus gambar saat ini dan buka ini?',
      'delete_drawing': 'Hapus gambar',
      'delete_drawing_complete': 'Gambar dihapus.',
      'delete_drawing_confirm': 'Hapus gambar ini?',
      'delete_error': 'Gambar tidak dapat dihapus.',
      'share_error': 'Gambar tidak dapat dibagikan.',
      'watercolor_brush': 'Kuas cat air',
      'airbrush_brush': 'Airbrush',
      'watercolor_mode': 'Mode cat air',
      'airbrush_mode': 'Mode airbrush',
      'brush_unlock_message': 'Tonton iklan singkat untuk membuka kuas ini.',
      'brush_unlocked': 'Kuas terbuka',
      'watch_ad': 'Tonton iklan',
      'nav_home': 'Beranda',
      'nav_gallery': 'Galeri',
      'nav_history': 'Riwayat',
      'nav_stats': 'Statistik',
    },
    'zh': {
      'app_name': '涂鸦画板',
      'app_subtitle': '自由绘画，轻松分享',
      'ask_before_clear': '清空前确认',
      'ask_before_clear_desc': '清除所有笔画前先确认',
      'back': '返回',
      'brush_guide': '画笔指南',
      'brush_guide_desc': '在下方选择画笔并调整粗细',
      'cancel': '取消',
      'clear': '清除',
      'clear_all': '全部清除',
      'clear_canvas': '清空画布',
      'clear_canvas_confirm': '要清空整个画布吗？',
      'clear_data': '清除本地数据',
      'clear_data_complete': '本地数据已清除。',
      'clear_data_confirm': '清除设置和历史记录吗？',
      'clear_data_desc': '重置设置和历史记录',
      'confirm': '确认',
      'data_and_support': '数据与支持',
      'drawing_settings': '绘画设置',
      'eraser_mode': '橡皮模式',
      'error': '错误',
      'exit': '退出',
      'exit_app_message': '已保存的画作会留在本机。',
      'exit_confirmation': '退出应用？',
      'feature_colors': '多种颜色',
      'feature_eraser': '橡皮',
      'feature_marker': '马克笔',
      'feature_pen': '画笔',
      'feature_share': '分享',
      'feature_undo': '撤销',
      'feedback': '发送反馈',
      'feedback_desc': '分享你的改进建议',
      'feedback_tip': '此功能正在准备中，感谢等待。',
      'feedback_email_subject': 'Doodle Pad 反馈',
      'haptic_feedback': '触觉反馈',
      'haptic_feedback_desc': '使用工具时振动',
      'history': '历史',
      'history_subtitle': '@screen / @route',
      'language': '语言',
      'no_history': '暂无历史记录。',
      'open_history': '历史',
      'open_history_desc': '查看之前的绘画和活动',
      'open_stats': '统计',
      'open_stats_desc': '查看应用使用和活动',
      'premium_benefit_remove_ads': '移除广告',
      'premium_benefit_statistics': '详细统计',
      'premium_benefit_unlimited': '无限绘画',
      'premium_benefits': 'Premium 权益',
      'premium_owned': '已开通 Premium',
      'premium_support_large_desc': '大力支持 Doodle Pad。',
      'premium_support_large_title': '大份支持',
      'premium_support_medium_badge': '热门',
      'premium_support_medium_desc': '移除广告并支持项目。',
      'premium_support_medium_title': '中份支持',
      'premium_support_small_desc': '为干净画布送上小小支持。',
      'premium_support_small_title': '小份支持',
      'premium_support_title': '支持 Doodle Pad',
      'premium_plan_monthly': '月度方案',
      'premium_plan_monthly_desc': '1 个月使用全部 Premium 功能',
      'premium_plan_title': '选择支持',
      'premium_plan_weekly': '周度方案',
      'premium_plan_weekly_desc': '1 周使用全部 Premium 功能',
      'premium_plan_yearly': '年度方案',
      'premium_plan_yearly_desc': '1 年使用全部 Premium 功能',
      'premium_purchase': '立即支持',
      'premium_purchase_note': '一次支持，广告持续移除。',
      'premium_ready': 'Premium 已可使用。',
      'premium_restore': '恢复购买',
      'premium_subtitle': '移除广告，支持后续更新。',
      'premium_title': 'Premium',
      'purchase_error': '无法完成购买。',
      'purchase_failed': '无法完成购买。',
      'purchase_success': '购买完成。',
      'purchase_unavailable': '当前无法购买。',
      'quick_actions': '快捷操作',
      'redo': '重做',
      'refresh': '刷新',
      'rate_app': '评价应用',
      'rate_app_desc': '在商店留下评价',
      'restore_error': '无法恢复购买。',
      'settings': '设置',
      'share': '分享',
      'show_brush_guide': '显示画笔指南',
      'show_brush_guide_desc': '在绘画工具栏下方显示提示',
      'start_drawing': '开始绘画',
      'stats': '统计',
      'today_events': '今天',
      'top_events': '主要活动',
      'total_events': '全部活动',
      'undo': '撤销',
      'unique_routes': '访问的页面',
      'unique_screens': '独立页面',
      'unknown_event': '未知活动',
      'week_events': '本周',
      'more_apps': '更多应用',
      'more_apps_desc': '查看 DangunDad 的更多应用',
      'privacy_policy': '隐私政策',
      'privacy_policy_desc': '查看数据和权限的处理方式',
      'link_open_error': '无法打开链接。',
      'save': '保存',
      'saved': '已保存',
      'save_canvas': '保存绘画',
      'save_success': '绘画已保存。',
      'save_error': '无法保存绘画。',
      'gallery': '图库',
      'gallery_empty': '还没有保存的绘画',
      'gallery_subtitle': '打开或分享保存的绘画',
      'saved_drawings': '已保存绘画',
      'load_drawing': '打开',
      'load_drawing_message': '以此图片为参考开始新绘画。',
      'load_drawing_confirm': '清除当前绘画并打开这张吗？',
      'delete_drawing': '删除绘画',
      'delete_drawing_complete': '绘画已删除。',
      'delete_drawing_confirm': '删除这张绘画吗？',
      'delete_error': '无法删除绘画。',
      'share_error': '无法分享绘画。',
      'watercolor_brush': '水彩笔',
      'airbrush_brush': '喷枪',
      'watercolor_mode': '水彩模式',
      'airbrush_mode': '喷枪模式',
      'brush_unlock_message': '观看短广告即可解锁此画笔。',
      'brush_unlocked': '画笔已解锁',
      'watch_ad': '观看广告',
      'nav_home': '首页',
      'nav_gallery': '图库',
      'nav_history': '历史',
      'nav_stats': '统计',
    },
    'ar': {
      'app_name': 'لوحة الرسم',
      'app_subtitle': 'ارسم بحرية وشارك بسهولة',
      'ask_before_clear': 'تأكيد قبل المسح',
      'ask_before_clear_desc': 'اطلب التأكيد قبل حذف كل الخطوط',
      'back': 'رجوع',
      'brush_guide': 'دليل الفرش',
      'brush_guide_desc': 'اختر الفرشاة من الأسفل واضبط الحجم',
      'cancel': 'إلغاء',
      'clear': 'مسح',
      'clear_all': 'مسح الكل',
      'clear_canvas': 'مسح اللوحة',
      'clear_canvas_confirm': 'هل تريد مسح اللوحة بالكامل؟',
      'clear_data': 'مسح البيانات المحلية',
      'clear_data_complete': 'تم مسح البيانات المحلية.',
      'clear_data_confirm': 'مسح الإعدادات والسجل؟',
      'clear_data_desc': 'إعادة ضبط الإعدادات والسجل',
      'confirm': 'تأكيد',
      'data_and_support': 'البيانات والدعم',
      'drawing_settings': 'إعدادات الرسم',
      'eraser_mode': 'وضع الممحاة',
      'error': 'خطأ',
      'exit': 'خروج',
      'exit_app_message': 'تبقى رسوماتك المحفوظة على هذا الجهاز.',
      'exit_confirmation': 'هل تريد الخروج؟',
      'feature_colors': 'ألوان متعددة',
      'feature_eraser': 'ممحاة',
      'feature_marker': 'قلم تحديد',
      'feature_pen': 'قلم',
      'feature_share': 'مشاركة',
      'feature_undo': 'تراجع',
      'feedback': 'إرسال ملاحظات',
      'feedback_desc': 'شارك أفكارك لتحسين التطبيق',
      'feedback_tip': 'هذه الميزة قيد التحضير. شكرًا لانتظارك.',
      'feedback_email_subject': 'ملاحظات Doodle Pad',
      'haptic_feedback': 'اهتزاز تفاعلي',
      'haptic_feedback_desc': 'اهتزاز عند استخدام أدوات الرسم',
      'history': 'السجل',
      'history_subtitle': '@screen / @route',
      'language': 'اللغة',
      'no_history': 'لا يوجد سجل بعد.',
      'open_history': 'السجل',
      'open_history_desc': 'عرض الرسومات والأنشطة السابقة',
      'open_stats': 'الإحصاءات',
      'open_stats_desc': 'عرض استخدام التطبيق والأنشطة',
      'premium_benefit_remove_ads': 'إزالة الإعلانات',
      'premium_benefit_statistics': 'إحصاءات مفصلة',
      'premium_benefit_unlimited': 'رسم بلا حدود',
      'premium_benefits': 'مزايا Premium',
      'premium_owned': 'Premium مفعّل',
      'premium_support_large_desc': 'دعم كبير لتطبيق Doodle Pad.',
      'premium_support_large_title': 'دعم كبير',
      'premium_support_medium_badge': 'رائج',
      'premium_support_medium_desc': 'إزالة الإعلانات ودعم التطبيق.',
      'premium_support_medium_title': 'دعم متوسط',
      'premium_support_small_desc': 'شكر بسيط للوحة نظيفة.',
      'premium_support_small_title': 'دعم بسيط',
      'premium_support_title': 'دعم Doodle Pad',
      'premium_plan_monthly': 'الخطة الشهرية',
      'premium_plan_monthly_desc': 'كل مزايا Premium لمدة شهر',
      'premium_plan_title': 'اختر الدعم',
      'premium_plan_weekly': 'الخطة الأسبوعية',
      'premium_plan_weekly_desc': 'كل مزايا Premium لمدة أسبوع',
      'premium_plan_yearly': 'الخطة السنوية',
      'premium_plan_yearly_desc': 'كل مزايا Premium لمدة سنة',
      'premium_purchase': 'ادعم الآن',
      'premium_purchase_note': 'دعم لمرة واحدة. تبقى الإعلانات محذوفة.',
      'premium_ready': 'Premium جاهز.',
      'premium_restore': 'استعادة المشتريات',
      'premium_subtitle': 'أزل الإعلانات وادعم التحديثات القادمة.',
      'premium_title': 'Premium',
      'purchase_error': 'تعذر إكمال الشراء.',
      'purchase_failed': 'تعذر إكمال الشراء.',
      'purchase_success': 'تم الشراء.',
      'purchase_unavailable': 'الشراء غير متاح الآن.',
      'quick_actions': 'إجراءات سريعة',
      'redo': 'إعادة',
      'refresh': 'تحديث',
      'rate_app': 'تقييم التطبيق',
      'rate_app_desc': 'اترك مراجعة في المتجر',
      'restore_error': 'تعذرت استعادة الشراء.',
      'settings': 'الإعدادات',
      'share': 'مشاركة',
      'show_brush_guide': 'إظهار دليل الفرش',
      'show_brush_guide_desc': 'إظهار التلميح أسفل شريط أدوات الرسم',
      'start_drawing': 'ابدأ الرسم',
      'stats': 'الإحصاءات',
      'today_events': 'اليوم',
      'top_events': 'أهم الأنشطة',
      'total_events': 'كل الأنشطة',
      'undo': 'تراجع',
      'unique_routes': 'الشاشات المزارة',
      'unique_screens': 'شاشات فريدة',
      'unknown_event': 'نشاط غير معروف',
      'week_events': 'هذا الأسبوع',
      'more_apps': 'المزيد من التطبيقات',
      'more_apps_desc': 'استكشف تطبيقات أخرى من DangunDad',
      'privacy_policy': 'الخصوصية',
      'privacy_policy_desc': 'اطلع على استخدام البيانات والأذونات',
      'link_open_error': 'تعذر فتح الرابط.',
      'save': 'حفظ',
      'saved': 'تم الحفظ',
      'save_canvas': 'حفظ الرسم',
      'save_success': 'تم حفظ الرسم.',
      'save_error': 'تعذر حفظ الرسم.',
      'gallery': 'المعرض',
      'gallery_empty': 'لا توجد رسومات محفوظة بعد',
      'gallery_subtitle': 'افتح رسوماتك أو شاركها',
      'saved_drawings': 'الرسومات المحفوظة',
      'load_drawing': 'فتح',
      'load_drawing_message': 'ابدأ رسمًا جديدًا باستخدام هذه الصورة.',
      'load_drawing_confirm': 'مسح الرسم الحالي وفتح هذا؟',
      'delete_drawing': 'حذف الرسم',
      'delete_drawing_complete': 'تم حذف الرسم.',
      'delete_drawing_confirm': 'هل تريد حذف هذا الرسم؟',
      'delete_error': 'تعذر حذف الرسم.',
      'share_error': 'تعذرت مشاركة الرسم.',
      'watercolor_brush': 'فرشاة ألوان مائية',
      'airbrush_brush': 'بخاخ',
      'watercolor_mode': 'وضع الألوان المائية',
      'airbrush_mode': 'وضع البخاخ',
      'brush_unlock_message': 'شاهد إعلانًا قصيرًا لفتح هذه الفرشاة.',
      'brush_unlocked': 'تم فتح الفرشاة',
      'watch_ad': 'مشاهدة إعلان',
      'nav_home': 'الرئيسية',
      'nav_gallery': 'المعرض',
      'nav_history': 'السجل',
      'nav_stats': 'الإحصاءات',
    },
  };
}
